make/test.mk
to get rid of parts like:
```
error: no token is currently in use for this session
```
and 
```
oc new-project toolchain-e2e-1570519386 --display-name e2e-tests
Now using project "toolchain-e2e-1570519386" on server "https://192.168.99.100:8443".
You can add applications to this project with the 'new-app' command. For example, try:
oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git
to build a new example application in Ruby.
```
=> chore: make the test setup output cleaner

make/test.mk, wait/awaitility.go
* use date timestamp as a suffix for locally build images
* improve logging of KubeFedCluster with insufficient conditions
* improve wait after installation via CSV
=> chore: add wait for CRD,improve logging and tag of local images

go.mod, go.sum, test/e2e/usersignup_test.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/91
=> Updated e2e tests to remove UserSignup.Spec.UserID

test/e2e/e2e_test.go, test/e2e/kubefed_test.go, test/e2e/nstemplateset_test.go, test/e2e/nstemplatetier_test.go, test/e2e/registration_service_test.go, test/e2e/usersignup_test.go, testsupport/doubles.go, testsupport/init.go
=> rename pkg 'doubles' to 'testsupport'

openshift-ci/Dockerfile.tools
Seems to be required for https://githuSb.com/codeready-toolchain/toolchain-e2e/pull/31
=> Install gcc in Dockerfile.tools

make/dev.mk, make/test.mk
The output will be:
```
...
Deployment complete!
Access the Landing Page here: https://registration-service-toolchain-host-operator.192.168.42.52.nip.io
To clean the cluster run 'make clean-e2e-resources'
...
```
=> Print Landing Page URL when deploying to dev env

make/test.mk, test/e2e/e2e_test.go, wait/awaitility.go, wait/member.go
E2E tests for https://github.com/codeready-toolchain/host-operator/pull/106
=> Tests for Namespaces and RoleBindings in NS Templates

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/registration_service_test.go, test/e2e/usersignup_test.go
As an admin, I want to see the user email when approving an account. This makes my work easier as I can see where the user is coming from (e.g. redhat.com).
**Relates to:**
jira - https://jira.coreos.com/browse/CRT-374
api - codeready-toolchain/api#69
host - codeready-toolchain/host-operator#115
reg - https://github.com/codeready-toolchain/registration-service/pull/82
=> Annotations

make/test.mk, test/e2e/e2e_test.go
See https://github.com/codeready-toolchain/host-operator/pull/119
=> Grant users admin role

test/e2e/e2e_test.go, wait/host.go, wait/member.go
=> add test to verify that namespaces are recreated by member operator controller

test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, test/e2e/user_management_test.go, wait/member.go
paired PR: https://github.com/codeready-toolchain/host-operator/pull/152
=> chore(CRT-475): verify team tier

go.mod, go.sum, test/e2e/nstemplatetier-basic.yaml, test/e2e/nstemplatetier_test.go, wait/host.go
e2e tests for https://github.com/codeready-toolchain/host-operator/pull/161
=> add assertion on NSTemplateTier.spec.clusterResource

tiers/checks.go, wait/member.go
updated the "provider" label
updates https://issues.redhat.com/browse/CRT-460
=> add limit ranges on namespace templates

tiers/checks.go, wait/member.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/164
Requires https://github.com/codeready-toolchain/member-operator/pull/133 to be merged first.
=> Isolate pods in user namespaces

make/test.mk, test/e2e/e2e_test.go, tiers/nstemplateset.go, tiers/revisions.go
paired PR: https://github.com/codeready-toolchain/member-operator/pull/135
=> fix: verify revisions of ClusterResources

make/test.mk
instead of using hardcoded url (that is changing lately) we can use a variable to load the image location
=> fix: use image location from variable

.gitignore, test/e2e/user_management_test.go, test/e2e/usersignup_test.go
paired PR: https://github.com/codeready-toolchain/host-operator/pull/176
=> chore: verify new transformation of compliant username

tiers/checks.go
paired PR: https://github.com/codeready-toolchain/host-operator/pull/177
=> chore: verify optimized limits across tiers

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/179
=> Tests for privilege escalation prevention

go.mod, go.sum, tiers/checks.go
Checking that the provider label is added to all inner resources. 
E2E-tests related to: https://github.com/codeready-toolchain/member-operator/pull/142
Jira story: https://issues.redhat.com/browse/CRT-495
=> Adding provider label

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/180
=> Add permissions to edit rbac for advanced tier

make/clean.mk, make/test.mk
This PR:
* adds  clean-toolchain-resources-in-dev target deleting the toolchain resources
* moves all clean* targets to clean.mk file
=> feat: add clean-toolchain-resources-in-dev and move clean targets to one file

tiers/checks.go
Paired PR: https://github.com/codeready-toolchain/host-operator/pull/189
=> chore: verify balanced values in LimitRanges/Quotas

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/197
=> Test for tuned resource limits

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/198
=> Tests for new Che/code limits

test/e2e/e2e_test.go
E2E tests for https://github.com/codeready-toolchain/host-operator/pull/201
=> feat: set TemplateRef in MUR spec

go.mod, go.sum, make/test.mk, test/e2e/notification_test.go, test/e2e/nstemplatetier_test.go, wait/awaitility.go, wait/host.go
E2E tests for https://github.com/codeready-toolchain/host-operator/pull/230
=> testing user namespace update

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, wait/host.go, wait/member.go
E2E Tests for https://github.com/codeready-toolchain/host-operator/pull/240
=> testing NSTemplateTier update progress

test/e2e/e2e_test.go, testsupport/user_setup.go, wait/member.go
See https://github.com/codeready-toolchain/host-operator/pull/267
Fixes https://issues.redhat.com/browse/CRT-778
=> test: verify user account is recreated

make/perf.mk, test/perf/perf_test.go
also, increase to 1k users instead of 10.
=> add makefile goal for perf tests

go.mod, go.sum, testsupport/user_setup.go
verify that approved=false label is set by registration service when UserSignup is being created
depends on https://github.com/codeready-toolchain/api/pull/186
paired with: https://github.com/codeready-toolchain/registration-service/pull/129
=> chore: verify that approved=false label is set when UserSignup is being created

go.mod, go.sum, test/e2e/e2e_test.go, testsupport/toolchain_status_assertions.go, wait/host.go
Verifies that counter counts all added/removed MasterUserRecords and UserAccounts
Paired with: https://github.com/codeready-toolchain/host-operator/pull/276
=> chore: verify that counter counts MURs and UserAccounts

test/e2e/user_management_test.go, testsupport/tier_setup.go, tiers/nstemplateset.go
properly wait until the changes are completely applied and finished
=> fix: flaky tests for tiers and deactivation

go.mod, go.sum, test/e2e/base_user_test.go, test/e2e/registration_service_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, testsupport/conditions.go, testsupport/user_setup.go, wait/host.go
verifies automatic approval and capacity management when using `HostOperatorConfig` CR
paired with: https://github.com/codeready-toolchain/host-operator/pull/288
depends on: https://github.com/codeready-toolchain/toolchain-common/pull/131
=> chore: verify automatic approval with capacity management

go.sum, test/perf/README.adoc, test/perf/perf_test.go
a `README.adoc` file to explain how the performance tests work and what is measured. Living in the repository instead of in a Google Docs, as per @MatousJobanek's request ;)
=> README to explain the performance tests

cmd/manager/main.go, go.mod, go.sum, test/e2e/registration_service_test.go, test/e2e/toolchaincluster_test.go, testsupport/init.go, testsupport/user_setup.go
=> chore: resolve linter issues

tiers/checks.go
Adjusted tests for https://github.com/codeready-toolchain/host-operator/pull/308
=> No idlers in advanced tier

test/e2e/user_workloads_test.go, tiers/checks.go, wait/member.go
E2E tests for https://github.com/codeready-toolchain/member-operator/pull/205
=> test: increase idler timeout and specify standalone pod name

test/e2e/user_management_test.go, wait/host.go
Fixes tests failures like this:
```
Error Trace:	user_management_test.go:127
Operation cannot be fulfilled on masteruserrecords.toolchain.dev.openshift.com "pupil": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestUserManagement/TestUserDeactivation
```
=> Fix flaky user deactivation tests

go.mod, test/e2e/e2e_test.go, test/e2e/user_management_test.go, test/perf/perf_test.go, testsupport/init.go, wait/awaitility.go, wait/metrics.go, wait/metrics_test.go
Updates the tests to verify the metrics exposed in https://github.com/codeready-toolchain/host-operator/pull/309
=> Test usersignup metrics

make/test.mk
use docker-push makefile target in all repos and pass the needed image tag as IMAGE_TAG variable
=> chore: use docker-push and pass value for IMAGE_TAG var

test/e2e/base_user_test.go, test/e2e/nstemplatetier_test.go, testsupport/tier_setup.go, testsupport/user_setup.go
wait until basic NSTemplateTier is updated before provisioning new users
=> fix: wait until basic NSTemplateTier is updated

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/324
=> Tests for Network Policy to allow ingress traffic from CRW namespace

test/e2e/usersignup_test.go
Fixes https://issues.redhat.com/browse/CRT-783
=> Add simple test for forbidden username transformation

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/335
=> Increase CPU limit to 10 cores

deploy/host-operator/secrets.yaml
Paired with https://github.com/codeready-toolchain/registration-service/pull/152
=> Move twilio phone number to secret

tiers/checks.go
Tests for change of basic tier's deactivation period to 30 days.
Related PR: https://github.com/codeready-toolchain/host-operator/pull/345
=> Change basic tier to 30 days deactivation

make/test.mk, test/e2e/registration_service_test.go
paired with https://github.com/codeready-toolchain/registration-service/pull/164 to make it working
=> fix: change registry.svc.ci.openshift.org to registry.ci.openshift.org

test/e2e/usersignup_test.go
paired with https://github.com/codeready-toolchain/host-operator/pull/360
=> chore: verify prevention of redhat & default prefixes

test/e2e/registration_service_test.go, testsupport/user_setup.go, tiers/checks.go, wait/host.go
paired with https://github.com/codeready-toolchain/host-operator/pull/363
=> chore: verify dropped count limits in basic tiers

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/364
=> Disable idler for team tier

test/e2e/usersignup_test.go
paired with https://github.com/codeready-toolchain/host-operator/pull/365
=> chore: verify users with sandbox prefix

test/e2e/registration_service_test.go, testsupport/user_assertions.go
Associated tests for https://github.com/codeready-toolchain/registration-service/pull/167
=> CRT-915 add test for encoded User IDs

tiers/checks.go
paired with https://github.com/codeready-toolchain/host-operator/pull/369
=> chore: verify pod count limit set to 50

go.mod, go.sum, testsupport/user_setup.go, wait/host.go
This PR fixes tests to work with the following PR:
https://github.com/codeready-toolchain/host-operator/pull/368
Signed-off-by: Shane Bryzak <sbryzak@gmail.com>
=> CRT-915 fixed tests

go.mod, go.sum
=> update to latest of toolchain-common

go.mod, go.sum, test/e2e/registration_service_test.go
Preventing the registration-service from creating signup resources for users who signup which contains the term crtadmin in their username.
Jira: https://issues.redhat.com/browse/CRT-913
Related PRs: codeready-toolchain/toolchain-common#151, https://github.com/codeready-toolchain/registration-service/pull/170, https://github.com/codeready-toolchain/host-operator/pull/373
=> test for crtadmin

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/380
=> Use the same limitrange in -code as in other NSs

test/e2e/registration_service_test.go
Minor change to remove an unnecessary line of code.
Signed-off-by: Shane Bryzak <shane@localhost.localdomain>
=> CRT-883 removed unnecessary label setting

testsupport/tiers/checks.go
https://issues.redhat.com/browse/CRT-1008
paired with https://github.com/codeready-toolchain/host-operator/pull/397
=> chore: increase cpu limit to 20 cores

multicluster_setup.adoc
=> fix env var in multicluster setup

test/e2e/usersignup_test.go
paired with https://github.com/codeready-toolchain/host-operator/pull/399
=> chore: verify that users with specific suffixes are not created

make/go.mk
Fixes - https://issues.redhat.com/browse/CRT-1041 
This PR allows to identify underlying and build
corresponding binaries as required
Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>
=> Add support for mutil-architecture

multicluster_setup.adoc
mention that `oc login` on each cluster is a prerquisite.
=> doc: improve multi-cluster setup doc

testsupport/tiers/checks.go, testsupport/wait/member.go
paired with: https://github.com/codeready-toolchain/host-operator/pull/411
=> chore: verify RHOAS limits

test/e2e/base_user_test.go, test/e2e/registration_service_test.go, test/e2e/user_management_test.go
Related host operator PR: https://github.com/codeready-toolchain/host-operator/pull/413
Fixes https://issues.redhat.com/browse/CRT-1006
=> Refactored tests to replace UserSignup Deactivated property with States

testsupport/tiers/checks.go, testsupport/wait/member.go
=> fix: wait for expected number of resources

go.mod, go.sum, setup/users/create_users.go, test/e2e/registration_service_test.go, test/e2e/user_management_test.go, testsupport/user_assertions.go, testsupport/user_setup.go
result of codeready-toolchain/api#234
related PRs (but not paired): 
https://github.com/codeready-toolchain/host-operator/pull/436
https://github.com/codeready-toolchain/registration-service/pull/190
=> fix: update API with fixed API rules

test/e2e/e2e_test.go, testsupport/wait/member.go
Tests for https://github.com/codeready-toolchain/member-operator/pull/250
=> Tests for autoscaling buffer

test/e2e/registration_service_test.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/445
=> Removed migration testing

go.mod, go.sum, test/e2e/registration_service_test.go, testsupport/wait/host.go
This PR updates the API and toolchain-common dependencies to the latest version
=> Updated API and toolchain-common to latest versions

.github/workflows/publish-operators-for-e2e-tests.yml
add the same workflow as is in other repos
=> feat: add publish-operators-for-e2e-tests.yml workflow

test/e2e/toolchainstatus_test.go
=> skip flaky test

make/test.mk, scripts/manage-host-operator.sh
Since the scripts will be moved to CICD repo, then all config files should be applied from makefile
=> chore: apply config files from makefile

scripts/manage-operator.sh
related: codeready-toolchain/toolchain-cicd#31
=> fix: use AUTHOR var in GH Actions

go.mod, go.sum, test/e2e/toolchainstatus_test.go, test/e2e/user_management_test.go, test/e2e/user_workloads_test.go, test/e2e/usersignup_test.go
Updates toolchain-common dependency to the latest version
=> Update to latest toolchain-common

scripts/manage-operator.sh
... because it causes more problems than it brings benefits
=> fix: drop author from tags

deploy/host-operator/dev/toolchainconfig.yaml
Enables automatic approval of usersignups when running in Dev mode
=> Enable automatic approval in dev environment

test/e2e/e2e_test.go, test/e2e/user_workloads_test.go, testsupport/wait/member.go
paired with https://github.com/codeready-toolchain/host-operator/pull/492
=> fix: flaky tests

test/e2e/nstemplatetier_test.go, testsupport/tiers/checks.go
paired with https://github.com/codeready-toolchain/host-operator/pull/491
=> chore: drop team tier

test/e2e/base_user_test.go, testsupport/user_setup.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/487
=> e2e tests for notification refactor

deploy/host-operator/e2e-tests/toolchainconfig.yaml, go.mod, go.sum
Updates ToolchainConfig for e2e to set the reg service replicas.
=> Set reg service replicas for e2e environment

.github/workflows/ci-build.yml, make/clean.mk, make/dev.mk, make/find-tools.mk, make/format.mk, make/lint.mk, make/run-cicd-script.mk, make/test.mk
we have unit tests on utility funcs declared in the `testsupport`
package, and we should run these tests when a PR is submitted
Fixes https://issues.redhat.com/browse/CRT-1192
=> feat: add makefile goal and GH Action to run unit tests

go.mod, go.sum, setup/operators/operators.go, setup/resources/create_resources.go, setup/templates/template.go, testsupport/wait/awaitility.go
see https://github.com/codeready-toolchain/toolchain-common/pull/211 and https://github.com/codeready-toolchain/member-operator/pull/298
=> refactor: remove usage of 'client.ToolchainObject'

test/e2e/nstemplatetier_test.go, testsupport/tiers/checks.go, testsupport/wait/host.go, testsupport/wait/member.go
Tests for codeready-toolchain/host-operator#534
=> Appstudio tier

go.mod, go.sum, testsupport/wait/diff.go, testsupport/wait/diff_test.go, testsupport/wait/host.go, testsupport/wait/member.go
see https://github.com/codeready-toolchain/toolchain-e2e/pull/400#issuecomment-953689054
=> assertions: improve diffs readability

go.mod, go.sum, test/e2e/base_user_test.go, test/e2e/user_management_test.go, test/e2e/user_workloads_test.go, test/e2e/usersignup_test.go
=> refactor NewSignupRequest func

go.mod, go.sum, test/e2e/nstemplateset_test.go, testsupport/tiers/nstemplateset.go, testsupport/user_assertions.go, testsupport/wait/member.go
E2E Tests for https://github.com/codeready-toolchain/member-operator/pull/309
=> decouple UserAccounts from NSTemplateSets

go.mod, go.sum, testsupport/signup_request.go, testsupport/user_assertions.go, testsupport/wait/host.go
Fixes https://issues.redhat.com/browse/CRT-1321
See also:
https://github.com/codeready-toolchain/api/pull/266
https://github.com/codeready-toolchain/host-operator/pull/539
=> refactor: add MasterUserRecord.Spec.TierName field

go.mod, go.sum
=> feat: Space CRD

go.mod, go.sum, make/test.mk, testsupport/init.go
related PR codeready-toolchain/toolchain-common#217
it also restarts host operator so it can get the created ToolchainCluster CRs
=> chore: update common dependency with cluster Config & restart host operator

go.mod, go.sum, testsupport/toolchain_status_assertions.go, testsupport/wait/host.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/551
=> feat: verify that Proxy URL is in ToolchainStatus CR

go.mod, go.sum, test/e2e/space_test.go, testsupport/wait/host.go, testsupport/wait/member.go
E2E tests for https://github.com/codeready-toolchain/host-operator/pull/548
Fixes https://issues.redhat.com/browse/CRT-1310
=> test: create/delete space and nstemplateset

test/e2e/nstemplatetier_test.go, testsupport/user_assertions.go
paired with https://github.com/codeready-toolchain/member-operator/pull/317
=> chore: don't expect User nor Identity to be present for AppStudio

test/e2e/proxy_test.go, testsupport/wait/member.go
is paired with: https://github.com/codeready-toolchain/member-operator/pull/321
=> chore: user & identity without owner label are not deleted

test/e2e/space_test.go
E2E Tests for https://github.com/codeready-toolchain/host-operator/pull/562
Fixes https://issues.redhat.com/browse/CRT-1392
=> feat: retarget space to another member cluster

test/e2e/space_test.go, testsupport/wait/member.go
E2E test for https://issues.redhat.com/browse/CRT-1383
=> test: set 'workspace' label on Space namespace

make/test.mk, test/e2e/nstemplatetier_test.go, testsupport/tier_setup.go, testsupport/wait/host.go
Summary of changes:
- Adds print debug make target for local source testing: `deploy-e2e-local-and-print-local-debug`
- Completes test `TestUpdateNSTemplateTierWithSpaces`
Related Issue: https://issues.redhat.com/browse/CRT-1314
Related PR: https://github.com/codeready-toolchain/host-operator/pull/568
=> Test tier updates for Spaces

testsupport/tiers/checks.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/574
=> Update services quota to 30

test/e2e/space_test.go, testsupport/wait/host.go
Addresses https://github.com/codeready-toolchain/toolchain-e2e/pull/451#issuecomment-1016797487
=> Get the latest copy of space before updating

go.mod, go.sum, test/e2e/spacebinding_test.go, testsupport/wait/host.go
verifies that SpaceBinding is deleted when either bound Space or bound MUR is deleted 
paired with: https://github.com/codeready-toolchain/host-operator/pull/575
=> chore: verify that SpaceBindingCleanup controller works

test/e2e/space_test.go
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/458/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1486124355187380224
=> fix: update Space CR with a check for conflicts

testsupport/tiers/checks.go
Test for https://github.com/codeready-toolchain/host-operator/pull/583
=> Add ComponentDetectionQuery to appstudio user SA role

go.mod, go.sum, testsupport/wait/host.go, testsupport/wait/member.go
=> refactor: rename Member.APIEndpoint field

testsupport/tiers/checks.go
verifies: https://github.com/codeready-toolchain/host-operator/pull/589
=> chore: verify SPI resources in appstudio-user-actions role

test/e2e/space_autocompletion_test.go, test/e2e/space_test.go, testsupport/space.go
paired with: https://github.com/codeready-toolchain/host-operator/pull/588
=> Verify SpaceCompletion controller

test/e2e/proxy_test.go, testsupport/user_assertions.go, testsupport/wait/member.go
e2e test for the fix of - https://issues.redhat.com/browse/CRT-1436
related PR: - https://github.com/codeready-toolchain/member-operator/pull/337
=> add provider label check to user and identity provisioning

testsupport/tiers/checks.go
=> fix diff when ClusterResourceQuota does not match

testsupport/tiers/checks.go
Signed-off-by: Pavel Macík <pavel.macik@gmail.com>
This PR:
* Updates the checks for SBO quotas based on https://github.com/codeready-toolchain/host-operator/pull/594
=> chore: include quota for SBO spec API

testsupport/tiers/checks.go
Test for https://github.com/codeready-toolchain/host-operator/pull/600
=> Add delete for spiaccesstokenbindings in appstudio tier

testsupport/cleanup/clean.go
minor changes in logging to identify failing object
=> minor changes in logging to identify failing object

test/e2e/space_cleanup_test.go
Reverts codeready-toolchain/toolchain-e2e#496
=> Revert "skip space cleanup test"

testsupport/tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/614
=> Drop counts for objects defined by CRDs from user quotas

testsupport/tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/615
=> Add WTO/CRW NetworkPolicy to -stage

make/test.mk
Reverts https://github.com/codeready-toolchain/toolchain-e2e/pull/511/commits/0d669299286c4ee4ac1ec5e495c4f758281faab2
=> Re-enable migration testing

setup/cmd/root.go
Adds an option to skip the idler setup. Useful for some specific cases where you want to set up multiple accounts and some workloads for testing in each account.
=> Add option to skip idler setup

test/e2e/nstemplatetier_test.go, test/perf/README.adoc, testsupport/wait/host.go
Paired with: https://github.com/codeready-toolchain/host-operator/pull/618
=> Remove TemplateUpdateRequests

test/e2e/space_autocompletion_test.go, test/e2e/space_cleanup_test.go, test/e2e/space_test.go, test/migration/verify/verify_migration_test.go, testsupport/space.go
=> refactor: remove/merge duplicate verify funcs

make/test.mk
install host operator first to fix flakiness with webhook creation
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_member-operator/352/pull-ci-codeready-toolchain-member-operator-master-e2e/1511604959953555456
=> fix: install host operator first

go.mod, go.sum, test/migration/verify/verify_migration_test.go, testsupport/wait/member.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/625
=> Update tests to reflect UserAccountSpecEmbedded removal

testsupport/tiers/checks.go
Duplicates https://github.com/codeready-toolchain/toolchain-e2e/pull/540
Paired with https://github.com/codeready-toolchain/host-operator/pull/627
=> Update the appstudio user actions role check with the new requirements

deploy/host-operator/e2e-tests/usertier-base.yaml, go.mod, go.sum, test/e2e/user_management_test.go, testsupport/init.go, testsupport/wait/host.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/632
Summary of changes:
- Test user tier update mechanism
- Verify all user tiers are created with correct values
Initial review was on https://github.com/codeready-toolchain/toolchain-e2e/pull/545
=> User tier test

make/appstudio.mk, make/dev.mk, test/e2e/space_autocompletion_test.go
https://coreos.slack.com/archives/CHK0J6HT6/p1651232326429989
=> fix(appstudio): use latest tag in CI

testsupport/signup_request.go
=> refactor: drop SignupRequest interface

test/e2e/parallel/registration_service_test.go
e2e tests for https://github.com/codeready-toolchain/registration-service/pull/264
=> refactor(err): insert space between message and details

testsupport/signup_request.go
=> test: restore method comments

testsupport/tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/645
=> Disable Idler for appstudio tier

testsupport/tiers/checks.go
https://github.com/codeready-toolchain/host-operator/pull/646
=> test: coverage of Allow appstudio users create configmaps

testsupport/spacebinding.go, testsupport/wait/host.go
see https://github.com/codeready-toolchain/host-operator/pull/644
=> test: do not expect more than 1 SpaceBinding per user and space

go.mod, go.sum, test/e2e/proxy_test.go, testsupport/user_assertions.go
Paired with https://github.com/codeready-toolchain/member-operator/pull/368
=> Update appstudio testing to use SkipUserCreation

test/e2e/parallel/space_test.go, testsupport/signup_request.go
=> test: do not verify space resource if not created at signup

go.mod, go.sum, testsupport/wait/diff_test.go
API update related to https://github.com/codeready-toolchain/api/pull/312 and paired with https://github.com/codeready-toolchain/host-operator/pull/650
=> Update api dependency

make/dev.mk, setup/README.adoc
https://coreos.slack.com/archives/CHK0J6HT6/p1654152305201659?thread_ts=1653915368.726209&cid=CHK0J6HT6
=> feat: add dev-deploy-latest target

go.mod, go.sum, test/e2e/parallel/registration_service_test.go, testsupport/signup_request.go, testsupport/wait/host.go
E2E Tests for https://github.com/codeready-toolchain/registration-service/pull/267
=> test: activation code endpoint and service

deploy/host-operator/dev/toolchainconfig.yaml, go.mod, go.sum, test/e2e/parallel/registration_service_test.go, testsupport/wait/host.go
verify that the `SocialEvent.Status.ActivationCount` field is
updated to the number of _approved_UserSignups associated with
the SocialEvent.
See https://github.com/codeready-toolchain/host-operator/pull/659
=> verify socialevent's status.activationCount

test/e2e/nstemplatetier_test.go
This is the follow up PR to https://github.com/codeready-toolchain/toolchain-e2e/pull/579
=> Re-enable tier items check

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/668
=> Increase ephemeral storage for HACBS

test/e2e/proxy_test.go
Tests for https://github.com/codeready-toolchain/registration-service/pull/275
There is no much new in this PR. Just running the same existing proxy tests multiple times to make sure that the cache kicks in.
=> Proxy cache

test/e2e/user_management_test.go, testsupport/conditions.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/667
=> Added tests for CRT-1569

testsupport/tiers/checks.go
This PR is paired with https://github.com/codeready-toolchain/host-operator/pull/675
Context https://issues.redhat.com/browse/SVPI-187
=> feat: SPI Grant an ability for the users to revoke/adjust granted authorization

go.mod, go.sum, setup/operators/operators.go, setup/resources/create_resources.go, setup/templates/template.go
=> refactor: no need for runtime.Scheme in ApplyClient

testsupport/tiers/checks.go
codeready-toolchain/host-operator#679
=> test: coverage of refactor of ReleaseLinks

test/e2e/nstemplatetier_test.go, testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/682
=> Tests for basenoidling tier

setup/README.adoc, setup/cmd/root.go, setup/configuration/configuration.go, setup/idlers/update_idler.go, setup/operators/installtemplates/devspaces.yaml, setup/resources/create_resources.go
- use base1ns space tier when creating users
- Update Dev Spaces operator to latest version
=> Update perf tool to use base1ns tier

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/681
=> Update tests for RHODS single namespace test.

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/693
=> Updating tests for updates to base1ns tier.

test/e2e/nstemplatetier_test.go, testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/699
=> Tests for base1ns6didler tier

go.mod, go.sum, setup/users/create_users.go, test/e2e/parallel/registration_service_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/perf/perf_test.go, testsupport/deactivation.go, testsupport/signup_request.go
see https://github.com/codeready-toolchain/toolchain-common/pull/277
=> refactor: usersignup approved funcs

testsupport/tiers/checks.go
paired with https://github.com/codeready-toolchain/host-operator/pull/707
=> verify dropped application prefix from AppStudio CRDs

go.mod, go.sum, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/socialevent_test.go, testsupport/cleanup/clean.go, testsupport/wait/host.go
E2E tests for https://github.com/codeready-toolchain/host-operator/pull/706
Fixes https://issues.redhat.com/browse/CRT-1613
=> fix: use SocialEvent's UserTier and SpaceTier when provisioning

testsupport/cleanup/clean.go
=> test: dump object when cleanup failed

test/e2e/proxy_test.go
Paired with https://github.com/codeready-toolchain/registration-service/pull/293
=> Update proxy test to verify compliant username usage

make/test.mk
this one saves the logs for all replicas in registration service deployment in a single file with the pod and container prefix name present in each line.
Example output:
```
....
[pod/registration-service-778c84479f-dvjjv/registration-service] {"level":"info", "client-ip":"5.171.212.78", "ts":"Fri, 16 Dec 2022 09:06:40 UTC", "method":"POST", "path":"/api/v1/signup", "proto":"HTTP/1.1", "status":"202", "latency":"23.672388ms", "user-agent":"Go-http-client/1.1", "error-message":""}
[pod/registration-service-778c84479f-dvjjv/registration-service] {"level":"info","ts":"2022-12-16T09:09:11.889Z","logger":"registration-service","msg":"user not found, creating a new one","encoded_user_id":"39833aca-6d4d-488d-953d-82312f527dc5","timestamp":"Fri, 16 Dec 2022 09:09:11 …
```
=> print logs for all replicas in registration service deployment

go.mod, go.sum, make/run-cicd-script.mk, test/e2e/toolchaincluster_test.go, testsupport/wait/awaitility.go
This PR tests that home label is added correctly to toolchaincluster of type member.
See Jira: https://issues.redhat.com/browse/ASC-245
Related PRs:
- toolchain-common: https://github.com/codeready-toolchain/toolchain-common/pull/284
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/722
- toolchain-cicd: https://github.com/codeready-toolchain/toolchain-cicd/pull/79
=> Roles as labels at ToolchainCluster CRD 

testsupport/tiers/checks.go
Signed-off-by: Romain Arnaud <rarnaud@redhat.com>
C.f. https://github.com/codeready-toolchain/host-operator/pull/739
=> Increase pod quota for AppStudio to 150

make/test.mk
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1676037197637649
=> do not label OLM namespace automatically

go.mod, go.sum, test/e2e/proxy_test.go
Tests for https://github.com/codeready-toolchain/registration-service/pull/304
=> Test Workspace Type and Object Metadata

.github/workflows/ci-build.yml, setup/cmd/root.go, setup/resources/create_resources.go, testsupport/tiers/checks.go, testsupport/wait/host.go
=> chore: upgrade GolangCI Lint to v1.52.0

testsupport/tiers/checks.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/778
=> Update tests for storage limit increase

testsupport/tiers/checks.go
* Add e2e tests for the new resource quotas
=> feat(STONEINTG-343): set ResourceQuota for Appstudio CRDs

make/test.mk, test/e2e/parallel/space_test.go, test/e2e/space_autocompletion_test.go
https://issues.redhat.com/browse/CRT-1775
paired PR: https://github.com/codeready-toolchain/host-operator/pull/791
=> disable unkown-cluster-related test

deploy/host-operator/appstudio-dev/toolchainconfig.yaml, deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
we do have it set in sandbox-sre, but not here
=> appstudio: set skipUserCreation to true

testsupport/cleanup/clean.go
improve message when UserSignup cleanup fails so we know what is exactly missing to be cleaned
=> improve message when UserSignup cleanup fails

testsupport/tiers/checks.go
paired with https://github.com/codeready-toolchain/host-operator/pull/796
=> PLNSRVCE-1167: add logs resource to tekton results RBAC

testsupport/tiers/checks.go
Re-creating PR #717 as it was originally created using a wrong branch name
Paired with https://github.com/codeready-toolchain/host-operator/pull/790
=> Increase cpu request to 3 for base1ns tier

testsupport/wait/host.go
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1682629533095989
=> check if SpaceBinding is being deleted

test/e2e/nstemplatetier_test.go, test/e2e/proxy_test.go
tests for https://github.com/codeready-toolchain/registration-service/pull/317
=> Test invalid proxy request headers

test/e2e/parallel/space_test.go, test/metrics/metrics_test.go, testsupport/metrics.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/804
=> Test user_signups_approved_with_method_total metric

testsupport/tiers/nstemplateset.go
part 2 for https://issues.redhat.com/browse/CRT-1797
=> fix: use updated nstemplateset

test/migration/setup_runner.go, testsupport/tiers/nstemplateset.go
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/codeready-toolchain_host-operator/805/pull-ci-codeready-toolchain-host-operator-master-e2e/1658440184355622912/build-log.txt
=> wait for SpaceRole when provisioning

testsupport/tiers/checks.go
paired with https://github.com/codeready-toolchain/host-operator/pull/812
=> Check for new mem limit

setup/idlers/update_idler.go, test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/serviceaccount_test.go, test/e2e/parallel/space_cleanup_test.go, test/e2e/parallel/space_test.go, test/e2e/parallel/spacerequest_test.go, test/e2e/parallel/web_console_plugin_test.go, test/e2e/proxy_test.go, test/e2e/space_autocompletion_test.go, test/e2e/user_management_test.go, test/e2e/user_rolebindings_test.go, test/e2e/user_workloads_test.go, test/e2e/usersignup_test.go, test/metrics/metrics_test.go, test/migration/setup_runner.go, test/migration/verify/verify_migration_test.go, testsupport/deactivation.go, testsupport/metrics.go, testsupport/signup_request.go, testsupport/space.go, testsupport/toolchain_status_assertions.go, testsupport/user_assertions.go, testsupport/wait/conditions.go
=> refactor: move conditions into 'testsupport/wait' pkg

go.mod, go.sum, test/e2e/e2e_test.go, testsupport/tiers/checks.go, testsupport/user_assertions.go, testsupport/wait/member.go
Check that new `SpaceLabelKey` is present on NSTeamplateResources
Jira:https://issues.redhat.com/browse/CRT-1776
Paired with: https://github.com/codeready-toolchain/member-operator/pull/438
=> fix: replace "owner" label with "space" label

deploy/host-operator/e2e-tests/toolchainconfig.yaml, test/e2e/parallel/registration_service_test.go
paired with : https://github.com/codeready-toolchain/host-operator/pull/813
removes the test to check woopra endpoint invoked.
=> remove woopra in paired PR

testsupport/tiers/checks.go
https://github.com/codeready-toolchain/host-operator/pull/811
=> Move to the new tekton sa

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/820
=> Add check for presence of remotesecret permissionsin adm in role for appstudio.

testsupport/tiers/checks.go
BuildPipelineSelector allows modify selection of pipelineRun for build.
https://github.com/codeready-toolchain/host-operator/pull/828
=> Appstudio: add access to buildpipelineselectors

testsupport/tiers/checks.go
Paired with: https://github.com/codeready-toolchain/host-operator/pull/825
Jira: https://issues.redhat.com/browse/SANDBOX-82
=> feat: se toolchain.dev.openshift.com/space as a selector in ClusterResourceQuotas

test/e2e/parallel/registration_service_test.go
Paired with https://github.com/codeready-toolchain/registration-service/pull/334
=> Tests for new usersignup get response

make/test.mk
see https://redhat-internal.slack.com/archives/CHK0J6HT6/p1689863736799519
=> fix: restart deployments after creating resources

test/e2e/parallel/spacerequest_test.go
paired with: https://github.com/codeready-toolchain/host-operator/pull/841
It doesn't actually validate that the kubeconfig has access to different member cluster then the one where the spacerequest resource is, it just validates that we can provision subspace on different member cluster then the one where parentSpace and spacerequest resource is.
=> fix: SpaceRequest SA token generation doesn't keep in account of the member cluster

test/e2e/parallel/serviceaccount_test.go, testsupport/wait/member.go
this PR addresses comments from https://github.com/codeready-toolchain/toolchain-e2e/pull/767
the only commit to be reviewed in this PR is: 5edc3160
=>  address comments from PR #767 

testsupport/tiers/checks.go
https://github.com/redhat-appstudio/book/pull/123
paired with https://github.com/codeready-toolchain/host-operator/pull/847
=> verify replacement of * by verbs in appstudio templates

testsupport/tiers/checks.go
Supports https://github.com/codeready-toolchain/host-operator/pull/853
=> Update admin spacerole role and rolebinding to indicate level

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/854
=> Let appstudio admins exec (rsh) to pods

testsupport/tiers/checks.go
paired PR https://github.com/codeready-toolchain/host-operator/pull/858
=> appstudio: verify limits of SpaceRequests and DT(C/S)s

dev_install.adoc
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1693460828997409
=> Fix & mention local targets, and remove quay username prefix

testsupport/tiers/checks.go
E2E tests for https://github.com/codeready-toolchain/host-operator/pull/859
Jira: https://issues.redhat.com/browse/ASC-412
=> feat: grant edit permissions over SBRs to RHTAP admis

testsupport/wait/member.go
Ops 🤦‍♂️  ... I realized that I forgot to enable this test!
paired with: https://github.com/codeready-toolchain/member-operator/pull/479
=> fix: enable webhook test check for sbr

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/parallel/retarget_test.go, test/e2e/parallel/space_test.go, test/e2e/usersignup_test.go, testsupport/signup_request.go, testsupport/user_assertions.go, testsupport/wait/host.go, testsupport/wait/member.go
paired PR https://github.com/codeready-toolchain/host-operator/pull/872
=> verify that targetClustersfor UserAccount is dynamically loaded

go.mod, go.sum, test/e2e/proxy_test.go
see: https://github.com/codeready-toolchain/api/pull/382
=> fix: binding request field should not be returned when empty

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/904
=> Increase resource quota for appstudio tier

testsupport/tiers/checks.go
Updated tests for https://github.com/codeready-toolchain/host-operator/pull/903
=> Check for additional CNV namespace policy

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/907
=> Align resource quota in base tier with base1ns

test/e2e/parallel/vm_webhook_test.go
tests for https://github.com/codeready-toolchain/member-operator/pull/490
=> Add VM cloud init user data test

test/e2e/nstemplatetier_test.go, testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/908
=> Introduce appstudio large tier

test/e2e/usersignup_test.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/928
=> Added migration test

test/e2e/parallel/user_rolebindings_test.go
moves user_rolebindings_test.go into parallel test suite
=> parallelize user rolebindings test

test/e2e/parallel/user_workloads_test.go
* transforms the user_workload_test from a test suite into a standard test
* moves the file into the parallel test suite
=> parallelize user workload test

testsupport/tiers/checks.go
Paired with: https://github.com/codeready-toolchain/host-operator/pull/936
=> Increase storage request limit for appstudo

test/e2e/parallel/e2e_test.go
move e2e_test.go into the parallel test suite
=> parallelize e2e test

test/e2e/parallel/web_console_plugin_test.go, testsupport/init.go
1. added forgotten `t.Parallel()` call in `web_console_plugin_test.go`
2. make sure that the WaitForDeployments is called only once for the whole test suite
=> wait for deployments once

test/e2e/parallel/proxy_test.go
move proxy_test.go into the parallel test suite
=> parallelize proxy test

go.mod, go.sum, testsupport/user_assertions.go
This is to Drop unused parameters from the embedded MUR.Status.UserAccounts.Clusters type
Related PRs
API - https://github.com/codeready-toolchain/api/pull/387
Host Operator - https://github.com/codeready-toolchain/host-operator/pull/925
=> Dropping the unused parameters

testsupport/user_assertions.go
Related PR: https://github.com/codeready-toolchain/member-operator/pull/507
=> Updated e2e tests for member operator - refactor UserAccountController to use PropagatedClaims

go.mod, go.sum, test/e2e/parallel/space_test.go, testsupport/space/space.go, testsupport/wait/host.go, testsupport/wait/member.go
replace toolchain-common for testing. https://github.com/codeready-toolchain/toolchain-common/pull/337
Also includes a new test for disabled inheritance with spaces.
=> test disabled inheritance for spaces

testsupport/wait/member.go
Fixes the comparison done to UserAccount spec to compare specs directly.
=> Fix useraccount comparison

go.mod, go.sum, test/e2e/parallel/registration_service_test.go
Paired with https://github.com/codeready-toolchain/registration-service/pull/391
=> Update jwt to v5

required_tools.adoc, setup/operators/installtemplates/ansible-automation-platform.yaml, setup/operators/operators.go
Adds AAP operator to perf setup tool
=> Add AAP operator to perf setup tool

.github/workflows/publish-operators-for-e2e-tests.yml
https://github.com/codeready-toolchain/registration-service/pull/394
=> check substrings of GH comments to run PR CD workflow

testsupport/wait/member.go
Tests for https://github.com/codeready-toolchain/member-operator/pull/527
=> Add ssp to webhook tests

test/e2e/parallel/proxy_test.go
E2E tests for: https://github.com/codeready-toolchain/registration-service/pull/387
Jira: https://issues.redhat.com/browse/ASC-443
=>  fix: add spacebindingrequests to workspace binding list

test/e2e/parallel/vm_webhook_test.go
Tests for https://github.com/codeready-toolchain/member-operator/pull/534
=> Test domain memory case

make/go.mk, test/e2e/parallel/vm_webhook_test.go
tests for https://github.com/codeready-toolchain/member-operator/pull/535
=> Test sandbox toleration

.github/dependabot.yml, .github/workflows/ci-build.yml, .github/workflows/publish-operators-for-e2e-tests.yml, .golangci.yml, setup/metrics/gather_test.go, setup/wait/wait_test.go, test/e2e/no_user_identity_test.go, test/e2e/parallel/e2e_test.go, test/e2e/parallel/nstemplatetier_test.go, test/e2e/parallel/proxy_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/retarget_test.go, test/e2e/parallel/spaceprovisionerconfig_test.go, test/e2e/parallel/user_rolebindings_test.go, test/e2e/parallel/vm_webhook_test.go, test/e2e/parallel/web_console_plugin_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/metrics/metrics_test.go, testsupport/metrics/metrics.go, testsupport/metrics/metrics_test.go, testsupport/tiers/checks.go, testsupport/user_assertions.go, testsupport/wait/awaitility.go, testsupport/wait/host.go, testsupport/wait/member.go
see docs at https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
see https://github.com/codeready-toolchain/sandbox-sre/pull/1578
=> chore: keeping our GitHub Actions up to date with Dependabot

make/run-cicd-script.mk, make/test.mk
to reflect & test changes from https://github.com/codeready-toolchain/toolchain-cicd/pull/102
=> reflect changes in add-cluster.sh script

test/e2e/parallel/space_test.go, test/e2e/parallel/spacebindingrequest_test.go
The current PR removes unnecessary assertions.
[SANDBOX-555](https://issues.redhat.com/browse/SANDBOX-555)
=> SANDBOX-555: remove unnecessary assertions

testsupport/tiers/checks.go
Paired with: https://github.com/codeready-toolchain/host-operator/pull/996
=> Increase appstudio tier pvc quota

setup/users/create_users.go, setup/users/create_users_test.go
Removing the leftover "type" Label
=> remove leftover "type" label

testsupport/tiers/checks.go
Tests for codeready-toolchain/host-operator#1004
=> feat: check for Konflux new Project* CRs

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/1016
[KFLUXBUGS-1235](https://issues.redhat.com//browse/KFLUXBUGS-1235)
=> Increase Konflux large tier pvc to 180

testsupport/tiers/checks.go
tests for https://github.com/codeready-toolchain/host-operator/pull/1023
=> Add tests for rhoai network policies

testsupport/tiers/checks.go
tests for https://github.com/codeready-toolchain/host-operator/pull/1024
=> Test updated quota for rhoai

make/test.mk, test/e2e/usersignup_test.go, testsupport/wait/conditions.go, testsupport/wait/host.go
Also adding new host wait conditions for config changes and some extra make targets to improve the time to reset operators on dev environment
paired with https://github.com/codeready-toolchain/host-operator/pull/1019
=> Adding e2e test cases for auto-approval domains

testsupport/space/space.go
This PR is very similar to PR #944, where we refactored the function `CreateSpaceAndSpaceBinding` to create first Space and SpaceBinding and just after add them to the clean up task. This PR does the same for function `CreateSpaceWithBinding`.
The refactor is needed since we are hitting [SANDBOX-593](https://issues.redhat.com/browse/SANDBOX-593) in the test `TestSpaceRoles`. The last occurrence was [yesterday](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_member-operator/562/pull-ci-codeready-toolchain-member-operator-master-e2e/1787437496703913984#1:build-log.txt%3A14935).
[SANDBOX-593](https://issues.redhat.com/browse/SANDBOX-593)
=> test: refactor CreateSpaceWithBinding function - create first Space and SpaceBinding and just after add them to the clean up task

go.mod, go.sum, test/e2e/no_user_identity_test.go, test/e2e/parallel/proxy_test.go, test/e2e/usersignup_test.go, test/metrics/metrics_test.go, testsupport/signup_request.go
This is updating the UUID pkg from `gofrs` to `Google`
Since in Toolchain - Common [PR](https://github.com/codeready-toolchain/toolchain-common/pull/395 ) it is already updated , Updating them in its related repos 
- Registration Service - https://github.com/codeready-toolchain/registration-service/pull/429
=> Update to Google uuid as changed in toolchaincommon

OWNERS
Signed-off-by: Feny Mehta <fbm3307@gmail.com>
=> Removing Michael's name from reviewers

test/e2e/parallel/proxy_test.go
[https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-tool[…]ady-toolchain-host-operator-master-e2e/1783223573393969152](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_host-operator/1016/pull-ci-codeready-toolchain-host-operator-master-e2e/1783223573393969152)
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1715865306943339
=> flaky: fix invalid SBR before cleanup

testsupport/tiers/checks.go
Tests update for https://github.com/codeready-toolchain/host-operator/pull/1037
=> Add ImageRepository CR permissions

test/e2e/parallel/spacebindingrequest_test.go
[SANDBOX-580](https://issues.redhat.com/browse/SANDBOX-580)
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1716912003579899
* reset the SpaceRole to a valid one so it can be removed quickly
* drop the test case with an invalid MUR - we cannot update MUR (webhook blocks that) and it could cause flakiness in the future.
=> fix flakiness: reset invalid SpaceRole to valid one in SBR

testsupport/signup_request.go, testsupport/space/spacerequest.go
Remove unnecessary standalone space creation. For more info, check PR #983 or [SANDBOX-629](https://issues.redhat.com/browse/SANDBOX-629).
[SANDBOX-629](https://issues.redhat.com/browse/SANDBOX-629)
=> test: SANDBOX-629: refactor CreateSpaceRequest

test/e2e/parallel/space_test.go, testsupport/signup_request.go
Remove unnecessary standalone space creation. For more info, check PR #983 or [SANDBOX-629](https://issues.redhat.com/browse/SANDBOX-629).
[SANDBOX-629](https://issues.redhat.com/browse/SANDBOX-629)
=> test: SANDBOX-629: refactor TestSpaceRoles and TestSubSpaces

test/e2e/toolchaincluster_test.go
Issue: https://issues.redhat.com/browse/KUBESAW-134
Associated PR: https://github.com/codeready-toolchain/member-operator/pull/582
This introduces the check for the presence of the kubeconfig in the ToolchainCluster secrets also to the member operator.
=> ToolchainCluster secrets should contain the kubeconfig in both host and member operators

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/1055
=> Forbid creating loadbalancer services

make/dev.mk
Signed-off-by: Francesco Ilario <filario@redhat.com>
=> fix: setup-dev-sso target

deploy/host-operator/e2e-tests/toolchainconfig.yaml, go.mod, go.sum, make/test.mk, testsupport/init.go, testsupport/wait/awaitility.go, testsupport/wait/member.go
Paired with https://github.com/codeready-toolchain/member-operator/pull/592
Requires https://github.com/codeready-toolchain/host-operator/pull/1071
=> Set CPU limit and request for Autoscaler Buffer

testsupport/wait/member.go
Paired with https://github.com/codeready-toolchain/member-operator/pull/593
=> Don't set limits for Autoscaler Buffer

README.adoc
https://github.com/codeready-toolchain/toolchain-e2e/pull/1030#pullrequestreview-2234831631
=> add ksctl note into REAME

make/ksctl.mk
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_registration-service/451/pull-ci-codeready-toolchain-registration-service-master-e2e/1823305161871724544#1:build-log.txt%3A1154
=> strip REMOTE_KSCTL_BRANCH variable value

make/run-cicd-script.mk, setup/operators/operators.go
Update subscription name.
Depends on: https://github.com/codeready-toolchain/toolchain-cicd/pull/120
=> update OLM subscription names

make/clean.mk
Add a target to get unstuck after a failed e2e test run with trailing e2e resources with finalizers and no operator running.
This may happen when the migration testsuite fails.
=> Add a target to get unstuck after a failed e2e test run

test/e2e/parallel/nstemplatetier_test.go, test/e2e/user_management_test.go, testsupport/tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/1100
=> Tests for intel tiers

test/e2e/parallel/proxy_test.go
Paired with https://github.com/codeready-toolchain/registration-service/pull/471
=> Allow proxy to forward requests to namespaces outside of workspace

setup/operators/installtemplates/pipelines.yaml
Update pipelines operator to 1.15 for perf test to match sandbox-sre
=> [perf] Update pipelines operator to 1.15

testsupport/tiers/checks.go
Paired with https://github.com/codeready-toolchain/host-operator/pull/1106
=> Increase storage quota to 60Gi

README.adoc, make/docker.mk, quay.adoc, required_tools.adoc
=> drop docker from docs and makefile

test/e2e/parallel/user_workloads_test.go
Updated idler test for https://github.com/codeready-toolchain/member-operator/pull/614
=> Test paused DeploymentConfig

make/ksctl.mk, openshift-ci/Dockerfile.tools, scripts/ci/manage-operator.sh
Update the author name and email address in the Dockerfiles so that the Docker image metadata reflects the correct contact information.
[SANDBOX-944](https://issues.redhat.com/browse/SANDBOX-944)
=> SANDBOX-944: update author in Dockerfiles

CODEOWNERS
=> project: add Rafaela, Feny and Lukas to CODEOWNERS

make/clean.mk
nice to have when testing the Workload Analyzer ;)
=> chore: remove BannedUsers during cleanup

test/e2e/parallel/nstemplatetier_test.go
to avoid flakiness we need to wait until the revision is updated also in the Tier
https://storage.googleapis.com/test-platform-results/pr-logs/pull/openshift_release/61582/rehearse-61582-pull-ci-codeready-toolchain-host-operator-master-e2e/1889811595995910144/build-log.txt
```
=== RUN   TestTierTemplateRevision/update_of_tiertemplate_should_trigger_creation_of_new_TTR
host.go:1083: waiting for ttrs to match criteria for tier 'ttr'
host.go:899: waiting until NSTemplateTier 'ttr' in namespace 'toolchain-host-12235743' matches criteria
nstemplatetier_test.go:568: 
Error Trace:	/tmp/toolchain-e2e/test/e2e/parallel/nstemplatetier_test.go:568
/tmp/toolchain-e2e/test/e2e/parallel/nstemplatetier_test.go:439
Error:      	Not equal: 
expected: &unstructured.Unstructured{Object:map[string]interface …
```
=> wait until TTR ref is updated in NSTemplateTier

test/e2e/parallel/user_workloads_test.go, test/e2e/parallel/vm_webhook_test.go, testsupport/signup_request.go
wrt: https://redhat-internal.slack.com/archives/CHK0J6HT6/p1741776384839269
=> flaky signup: fix nil check

CODEOWNERS, OWNERS
JIRA: https://issues.redhat.com/browse/SANDBOX-1043
=> chore: Remove Kanika from owners

testsupport/wait/member.go
Paired with https://github.com/codeready-toolchain/member-operator/pull/646
=> Update the autoscaler-buffer image registry

test/e2e/parallel/nstemplatetier_test.go, testsupport/tiers/checks.go, testsupport/wait/host.go
`$TITLE`
Related PRs:
- host-operator: https://github.com/codeready-toolchain/host-operator/pull/1191
JIRA: https://issues.redhat.com/browse/SANDBOX-1370
=> [SANDBOX-1370] remove the rest of the unused ns template tiers

test/e2e/parallel/nstemplatetier_test.go
fixing the number of ttr to be checked 
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1753440934539929
=> Fix Test case failure of testtiertemplate

make/test.mk
We need to disable UI E2E Tests until we also deploy the Developer Sandbox UI image trough gh action on host,  member, and registration side
https://github.com/codeready-toolchain/toolchain-cicd/pull/154
=> disable ui e2e tests
