codeready-toolchain/toolchain-e2e

README.adoc, make/test.mk
when the makefile tries to log in, it first checks if there is running VM via CRC. 
* If there is, then it tries to log in as `kube:admin`
* if there is no CRC VM running, then it logs as `system:admin`
=> feat: add support for CodeReady Containers

e2e/e2e_test.go, wait/host.go, wait/member.go
somehow, while moving the e2e tests, I missed the deletion test case. This PR merges:
https://github.com/codeready-toolchain/host-operator/blob/08e3262b122db594b4e06f93f077112d1e265cec/test/e2e/masteruserrecord_test.go#L79-L96
and 
https://github.com/codeready-toolchain/member-operator/blob/0fce69b64078055ef51c2ca33e793bc7c86ac33f/test/e2e/useraccount_test.go#L115-L131
=> fix: add missing delete case

make/test.mk
* when the e2e tests are running locally, then it builds the operator images using docker
* when the e2e tests are executed from another repo (in openshift-ci) and the image name of the operator is provided via either `HOST_IMAGE_NAME` or `MEMBER_IMAGE_NAME` variable, then it should use it because it's already built in the registry.
=> fix: use local image if running locally or provided if executed from another repo

make/test.mk, openshift-ci/Dockerfile.host.deploy, openshift-ci/Dockerfile.member.deploy
We need to let CI build both operators images before the actual e2e test execution so we have correct images to deploy
see this PR: https://github.com/openshift/release/pull/5140
=> fix: let CI build operators images before e2e test execution

make/test.mk
This PR is built on top of https://github.com/codeready-toolchain/toolchain-e2e/pull/3 - the only commit introducing changes is 39c1b06  
The commit adds changes that waited for this PR https://github.com/openshift/release/pull/5140 to be merged
It completes the whole fix of using/building operator images
=> chore: finish the fix of using/building operator images

make/test.mk
when the e2e tests are cloned & triggered inside of a job running for different repository (host-operator or member-operator) then it should not try to pair, because the found sha commit won't match any branch name
The impact of the bug can be seen here https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/codeready-toolchain_member-operator/72/pull-ci-codeready-toolchain-member-operator-master-e2e/306
=> fix: when it is executed from remote repo, then don't pair

make/test.mk
Instead of directly deploying host operator it adds it to Catalog and then installs as a standard operator
Paired PR: codeready-toolchain/member-operator#77
=> chore(CRT-226): deploy and install member-operator via CSV

.golangci.yml, make/lint.mk
add 'golangci.yml' file with a timeout to 10min
and the same linter config as in 'host-operator'
repo for now
Fixes CRT-299
=> configure golangci-lint

make/test.mk
this fixes the `-ldflags -X <path>=<value>`
and gives valid Commit and BuildTime info
in the deployed operators
Fixes CRT-282
=> update clone path to include repo org

make/test.mk
...so the e2e tests don't fail when the deployment/installation takes a longer time
=> chore: increase wait limit for resources after deployment

README.adoc, make/test.mk
* adds info to the README that the user needs to log in to quay.io when using OS 4.2
* removes unnecessary printing
* when the e2e tests are triggered from the `registration-service` repo, then it sets `IS_OTHER_IMAGE_SET` appropriately 
* adds printing info about the image and namespace that is used for the particular repository
* removes `build-and-deploy-service` target
* slightly modifies `build-and-deploy-operator` target so it can be used for `registration-service` too
paired with: https://github.com/codeready-toolchain/registration-service/pull/59
=> fix: use correct images when triggered from reg-service repo

doubles/init.go, go.mod, go.sum, make/test.mk, test/e2e/e2e_test.go, test/e2e/kubefed_test.go, test/e2e/nstemplateset_test.go, test/e2e/nstemplatetier_test.go, test/e2e/registration_service_test.go, test/e2e/usersignup_test.go, wait/awaitility.go
waits for the registration service deployment to be ready
and for the route to be available (as part of the setup),
then during the test, just make sure that the homepage is
available (returning a '200 OK' response)
Fixes CRT-322
=> add smoke test for the registration service

make/test.mk
* call `clean-e2e-resources` at the end of the tests to cleanup the cluster
* drop unnecessary `e2e-cleanup` target
=> fix: clean properly the cluster

test/e2e/e2e_test.go, wait/host.go, wait/member.go
the wait functions re-used the same instance of the resource for all `Get` calls, which means that when it got it, then it rewrote the existing values in the instance... But when there was a new version of the `Status.Condition` that didn't contain `Message`, but the previous one did contain, then there was nothing that would be used for rewriting the old message, so it kept the old one.
The flow looked like:
at one time the wait function got :
```
Status:{Conditions:[{Type:Ready Status:False LastTransitionTime:2019-11-12 14:08:49 +0100 CET Reason:UnableToProvisionNamespace Message:Operation cannot be fulfilled on namespaces "extrajohn-3-stage": the object has been modified; please apply your changes to the latest version and try again}]}
```
Then the status was updated to
``` …
```
=> fix: use new instance when getting resources in wait functions

README.adoc, make/dev.mk, make/test.mk
It will be useful when developing operators and/or registration service:
- `make dev-deploy-e2e-local` - deploys the same resources as `make test-e2e-local` but doesn't run tests.
- `make dev-deploy-e2e` - deploys the same resources as `make test-e2e` but doesn't run tests.
Be default instead of using generated NS names it uses `toolchain-host/member-operator` namespaces.
From reg-service/host/member repos these targets can be re-used to deploy everything using just one command.
For example from reg-service repo: `make deploy-e2e` will download everything but the reg-service itself and deploy it to OpenShift cluster - https://github.com/codeready-toolchain/registration-service/pull/70
=> Add makefile targets to deploy e2e resources without running tests

make/dev.mk, make/test.mk
Because of specifics of how makefile handles conditions (it evaluates them when it reads a makefile, not during execution) we can't use what was suggested in https://github.com/codeready-toolchain/toolchain-e2e/pull/44#discussion_r345638185
We have to use `$(MAKE) <some-target> VAR=${value}` constructions instead.
As side affect of this issue currently `make dev-deploy-e2-local` target deletes the local host/member/reg-service repos and re-clones them from github!
=> Properly pass variables when running dev-deploy targets

test/e2e/usersignup_test.go, testsupport/init.go, wait/awaitility.go, wait/host.go, wait/member.go
For example if we need to override the default timeout:
```
s.hostAwait.WithRetryOptions(TimeoutOption(time.Second * 10)).WaitForMasterUserRecord(...)
```
It's useful in test which wait for some resource not to be created and we don't want to wait for the entire default 120 seconds in such tests.
=> Allow individual tests override wait timeouts and retry intervals 

make/test.mk
The goal of `display-eval` is to provide a convenient way to retrieve the latest host and member operator namespaces on a cluster, and optionally, to export them as env vars:
```
$ make display-eval
export HOST_NS=host-operator-1574156115
export MEMBER_NS=member-operator-1574156115
export REGISTRATION_SERVICE_NS=$HOST_NS
```
The `host-operator-xxx` and `member-operator-xxx` projects are now labelled with `app=host-operator` and `app=member-operator` respectively the latest occurrence is retained. 
By querying the cluster, we can use this goal alone, without interfering with the `HOST_NS` and `MEMBER_NS` variables set in the `test.mk` file.
=> makefile goal to display the latest e2e project names

make/test.mk
move SA, RBAC and namespace name definition into the registration service deployment template
paired PR: https://github.com/codeready-toolchain/registration-service/pull/75
=> chore(CRT-361): reg-service SA and namespace name is moved to deployment

go.mod, go.sum
This PR is purely to verify that the changes in API and common do not break the member operator:
https://github.com/codeready-toolchain/api/pull/66
https://github.com/codeready-toolchain/toolchain-common/pull/65
When the PR from above are merged I will remove the replace and update the api and common dependencies properly.
=> Remove deprecated TargetCluster from MUR status

make/test.mk
adds a check that detects if there are multiple branches found while getting the branch name the PR is created for. If multiple branches are found, then it fails with:
```
###################################  ERROR DURING THE E2E TEST SETUP  ###################################
There were found more branches with the same latest commit 'd98a6058bef952cc2e88156f2d3105c9662a6964' in the repo https://github.com/MatousJobanek/toolchain-e2e - see:
0047d98a6058bef952cc2e88156f2d3105c9662a6964 refs/heads/another-branch
0053d98a6058bef952cc2e88156f2d3105c9662a6964 refs/heads/fail-for-multiple-branches
It's not possible to detect the correct branch this PR is made for.
Please delete the unreleated brach from your fork and rerun the e2e tests …
```
=> fix: fail if multiple branches are found

make/test.mk
adds a check that fails when it finds more branches from multiple repositories (host-operator, member-operator, registration-service) the PR could be paired with - we should support a case when there is only one branch from one repository paired with a PR. 
When such a case is detected, then it fails with:
```
####################################  ERROR WHILE TRYING TO PAIR PRs  ####################################
There was an error while trying to pair this e2e PR with https://github.com/MatousJobanek/toolchain-e2e@refs/heads/fail-for-multiple-paired-branches
The reason is that there was alraedy detected a branch from another repo this PR could be paired with - see:
repository: https://github.com/MatousJobanek/member-operator 
branch: fail-for-multiple-paired-branches
It's not possible …
```
=> fix: fail if multiple branches for pairing are detected

test/e2e/e2e_test.go, wait/member.go
E2E tests for:
https://github.com/codeready-toolchain/host-operator/pull/125
Requires https://github.com/codeready-toolchain/member-operator/pull/109 to be merged first to pass the tests.
=> Reduce user permissions

openshift-ci/Dockerfile.tools
`yq` binary is needed in the script introduced here codeready-toolchain/api#88. The script will be then used as part of the e2e test setup - see here: #65
=> chore: install github.com/kislyuk/yq binary

make/test.mk
This is a paired PR for https://github.com/codeready-toolchain/host-operator/pull/136 and also uses the functionality of the script introduced here: https://github.com/codeready-toolchain/api/pull/88.
The changes use the script and enriches either CSV or deployment YAML file by registation-service environment variables that are set in `deploy/env/<environment>.yaml` configuration files. 
In addition, it also stores the images in `/tmp/crt-e2e-image-names/` directory and then sets the registation-service image location to the host-operator YAML file as a variable ` REPLACE_REGISTRATION_SERVICE_IMAGE`
To verify that the variables are properly set please check the output of the build that intentionally failed: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/codeready-toolchain_tool …
=> feat(CRT-363): load config env files using enrich-by-envs-from-yaml.sh script

go.mod, make/dev.mk, test/e2e/kubefed_test.go, testsupport/init.go, wait/awaitility.go, wait/member.go
fixes #CRT-406
e2e tests for https://github.com/codeready-toolchain/host-operator/pull/139
=> feat: select first member cluster ready and with capacity

make/dev.mk, make/test.mk
use `${QUAY_NAMESPACE}` as a prefix for namespaces and as a suffix for subscriptions
* this will allow us running (and cleaning) e2e tests in parallel in one cluster 
* will avoid any conflicts with namespaces created in other clusters (eg. if we are accidentally logged to crt dev clusters :-))
=> chore: use ${QUAY_NAMESPACE} prefix/suffix for namespaces and subscriptions

make/dev.mk, make/test.mk, testsupport/init.go
based on the changes proposed in this PR https://github.com/codeready-toolchain/host-operator/pull/117 it changes the way the registration-service is being deployed. As the deployment is moved to host-operator, the e2e setup only builds the image and sets the appropriate host deployment params
=> feat(CRT-354): let host-operator deploy the registration service

make/test.mk
To properly verify that the changes introduced here https://github.com/codeready-toolchain/api/commit/d37dc262950f4345055d85c3d7e2aa8ba88c819a are working properly (in other words, that CSV and OLM can use digests instead of tags) use digests instead of tags in e2e tests too
=> chore: use digest instead of tags

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/usersignup_test.go, wait/member.go
Tests related to: https://github.com/codeready-toolchain/host-operator/pull/146
Deprecating Embedded UserAccount ID and UserAccount Disabled fields.
Relates to Jira task: https://issues.redhat.com/browse/CRT-455
Relates to Jira story: https://issues.redhat.com/browse/CRT-456
This will be done in three stages:
Deprecate Embedded UA ID/Disabled
PRs:
codeready-toolchain/api#100
#143
Change the implementation and start using the new API. Roll out to prod.
Delete deprecated API.
This PR is part of stage 2.
=> fixing tests

tiers/checks.go
verify that we use `rbac-edit` role name instead of `toolchain-*-edit` name
paired PR: https://github.com/codeready-toolchain/host-operator/pull/166
=> chore: verify role name rbac-edit

openshift-ci/Dockerfile.tools
Reverts codeready-toolchain/toolchain-e2e#89
`operator-sdk test local` (0.16.0) fails with:
```
flag provided but not defined: -skipCleanupOnError
```
I'm reverting the operator-sdk upgrade until this problem is investigated and fixed.
=> Revert "Update operator-sdk to 0.16.0"

make/test.mk, test/e2e/base_user_test.go, test/e2e/e2e_test.go, test/e2e/kubefed_test.go, test/e2e/nstemplateset_test.go, test/e2e/registration_service_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, testsupport/cleanup_options.go, testsupport/init.go
framework.TestCtx has been deprecated in Operator SDK 0.16.0.
See https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#breaking-changes-2
=> chore: replace 'framework.TestCtx' with 'framework.Context'

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/registration_service_test.go
In order to customize notification messages to users, we require additional user information which we should store in the UserSignup CRD when the user first registers. The new fields being added for the notification service messages are givenName, familyName and company. This PR will test that the fields were set correctly in the usersignup CRD via invoking the http post in registration service.
related to: https://github.com/codeready-toolchain/registration-service/pull/102
jira: https://issues.redhat.com/browse/CRT-518
=> Extracting additional user information

make/dev.mk, make/test.mk
* don't create new OLM resources for every `dev-deploy-e2e*` run - use the same name suffix
* if the operator namespace already contains the CSV then update it to force the redeployment
=> feat: if the operator CSV already exists then update it

test/e2e/e2e_test.go
https://issues.redhat.com/browse/CRT-216
Updates the e2e tests to look for the IdP `testIdP` that is configured in the env yaml file for the e2e-tests. See https://github.com/codeready-toolchain/member-operator/pull/150 for details.
=> Update for IdP configured for e2e environment

tiers/revisions.go
This PR removes the `ClusterResources` constant because:
* it wasn't used anywhere
* it contained capital "R" but the type name should contain only lower case letters
* to avoid any confusions with the correct name
=> chore: remove ClusterResources constant

openshift-ci/Dockerfile.tools
Changes the version of operator-sdk from 0.16.0 to 0.17.1
=> chore: use operator-sdk 0.17.1

make/test.mk
1. The test makefile has
`IS_KUBE_ADMIN := $(shell oc whoami | grep "kube:admin")`
`$(IS_KUBE_ADMIN)` is not empty if you are logged in as the `kube:admin` user so I think the check in the `login-as-admin` target should be `ifeq ($(IS_KUBE_ADMIN),)`
2. The previous code attempted to log in using `oc login -u=kubeadmin -p=`cat ~/.crc/cache/crc_libvirt_*/kubeadmin-password` 1>/dev/null` however, I have CRC 1.10.0 and that file does not exist so the login doesn't work. 
```
crc version: 1.10.0+9025021
OpenShift version: 4.4.3 (embedded in binary)
```
=> Fix CRC admin check

go.mod, go.sum, test/e2e/conditions.go, test/e2e/e2e_test.go, test/e2e/notification_test.go, wait/awaitility.go, wait/host.go
E2E tests for notification. 
Due to the notification being cleaned up now in the notfication controller, we can no longer verify the notification as part of `verifyResourcesProvisionedForSignup.` This is because we call `createMultipleSignups` and `createAndApproveSignup` at the start of the test. when the notifications are created `verifyResourcesProvisionedForSignup` will pass for the first notification. However, for the subsequent notifications this would fail because the notification controller would have already deleted the other notifications since the deletion time would have passed. This would cause us to be stuck attempting to retrieve notifications. 
In order to work around this issue, i've moved the notification tests into a new file called `notification_test.` If there is a …
=> addressing pr comments

go.sum, test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, wait/member.go
When we compare UserAccount with MUR we need to use the latest version of MUR, otherwise, the test of NSTempalteTier updates can fail: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/codeready-toolchain_host-operator/239/pull-ci-codeready-toolchain-host-operator-master-e2e/1278939436381376512/build-log.txt
What happened?
1. User `cheesecakelover01` was provisioned and promoted to `cheesecake` tier containing basic templates
2. Test updated `cheesecake` Tier to use advanced template
3. There was synchronization between UserAccount and MUR of the `cheesecakelover01` user that changed the `SyncIndex`
4. Test loaded MUR with changed `SyncIndex` and in `Provisioned` state and saved the MUR (still with basic templates) in a var
5. Test started waiting for UserAccount having advanced …
=> fix(flaky test): test should use latest MUR when comparing with UA

go.mod, go.sum, test/e2e/conditions.go, test/e2e/e2e_test.go, wait/host.go, wait/member.go
Updates the main e2e test to verify the overall toolchain status (ToolchainStatus resource)
The verification step verifies that the toolchain status exists and has the AllComponentsReady condition which means the member clusters, registration service and host operator are all ready.
Related PR: https://github.com/codeready-toolchain/host-operator/pull/241
=> Add test for toolchainstatus

test/e2e/nstemplatetier_test.go, tiers/checks.go, wait/member.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/245
These tests only checks that Idler resources are created during user provisioning. The Idler controller tests are more tricky to implement.
First at all there is no easy way of configuring a shorter timeout for idling (vs. 8 hours which are specified in all tiers).
Also, the tests might take awhile to execute because we would want to create many pods (with different controllers like Deployment, ReplicaSet, etc). Wait for them to start. And then wait for them to be killed.
Idler controller is pretty well covered by unit tests. So, not sure if it's that critical for us to introduce complex and slow e2e tests for full e2e coverage right now.
Any thoughts?
=> Tests for Idler

test/e2e/nstemplatetier_test.go, tiers/nstemplateset.go
It covers the cases when only a subset of NSTemplateSet is changed - either only ClusterResources or Namespace template refs
Paired with https://github.com/codeready-toolchain/member-operator/pull/183
=> fix(CRT-746): cover cases when subsets of TemplateRefs are changed

README.adoc
Updates the README to reflect the changes made in https://github.com/codeready-toolchain/toolchain-e2e/pull/61. It also explains the reason for the behaviour.
=> chore: Update README to correct branch pairing instructions

test/e2e/e2e_test.go
This PR replaces testIdP with rhd. The default idp is rhd. 
Related PR: https://github.com/codeready-toolchain/member-operator/pull/182
Jira: https://issues.redhat.com/browse/CRT-743
=> updating test to use rhd instead of testIdP

test/e2e/base_user_test.go, test/e2e/e2e_test.go, test/e2e/notification_test.go, test/e2e/nstemplatetier_test.go, test/e2e/registration_service_test.go, test/e2e/toolchaincluster_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, testsupport/conditions.go, testsupport/toolchain_status_assertions.go, testsupport/user_assertions.go, testsupport/user_setup.go
Moved the setup and assertions funcs in `testsupport` so we can later introduce a `test/perf` package and reuse the funcs.
=> refactor: move setup and assertions in 'testsupport'

test/e2e/e2e_test.go, testsupport/metrics_server_assertions.go, wait/host.go
check that there is a service called 'host-operator-metrics'
in the host operator namespace.
see https://github.com/codeready-toolchain/host-operator/pull/262
=> verify that 'host-operator-metrics' exists

test/e2e/e2e_test.go, testsupport/metrics_server_assertions.go, wait/member.go
E2E tests for https://github.com/codeready-toolchain/member-operator/pull/188
=> verify that 'member-operator-metrics' exists

go.mod, make/perf.mk, test/perf/perf_test.go
messages written in `stdout` are not retained after the job
completions on OpenShift CI, so we need to write the results
in a file in `$(ARTIFACT_DIR)`
Fixes https://issues.redhat.com/browse/CRT-799
=> perf: write results in a file in ARTIFCAT_DIR

test/perf/perf_test.go
use more meaningful field names for the logs
(using snake case)
=> refactor perf logs

go.mod, go.sum, testsupport/toolchain_status_assertions.go, wait/host.go, wait/member.go
Verifies that resource usage is set in `MemberStatus` CR - the propagation to `ToolchainStatus` CR will be verified later when the necessary changes are applied to `ToolchainStatus` controller.
paired with https://github.com/codeready-toolchain/member-operator/pull/198
=> chore: verify resource usage in MemberStatus

test/e2e/nstemplatetier_test.go, test/e2e/user_management_test.go, testsupport/conditions.go, testsupport/tier_setup.go
e2e tests for the new auto deactivation controller.
Summary of the changes:
- Refactored some of the code to reuse functions related to creating and manipulating tiers
- Added a new test for verifying that auto deactivation triggers user deactivation
Paired with https://github.com/codeready-toolchain/host-operator/pull/281
=> Add auto deactivation test

testsupport/toolchain_status_assertions.go
verify that ToolchainStatus collects resource usages
paired with: https://github.com/codeready-toolchain/host-operator/pull/285
=> feat: verify that ToolchainStatus collects resource usages

make/clean.mk
use `oc wait` to make sure that all resources
are deleted before deleting the projects.
=> improve e2e resource cleanup

test/e2e/user_management_test.go
This PR changes the following:
- modifies the auto deactivation test to also verify that the auto deactivation exclusion list works correctly by creating a new user that uses the `@excluded.com` domain and verifying that it is not auto deactivated
=> Add test for deactivation exclusion list

test/e2e/registration_service_test.go, testsupport/user_setup.go
This PR accompanies https://github.com/codeready-toolchain/host-operator/pull/293 and contains fixes to the e2e tests to allow them to continue to pass when phone verification is enabled.
=> Allow tests to still pass when phone verification enabled

test/e2e/toolchaincluster_test.go, testsupport/user_setup.go
The main change is in the `user_setup.go` - it cleans the UserSignup that is created through the registration service - until now, the UserSingups weren't deleted and stayed in the cluster.
=> chore: clean resources using testing.T.Cleanup function

go.mod, go.sum, test/e2e/registration_service_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, testsupport/conditions.go, testsupport/user_assertions.go, testsupport/user_setup.go, wait/host.go
verifies that UserSignup has the corresponding values of the `state` label set
removes `createUserSignupAndAssertPendingApproval` function since it wasn't used anywhere
paired with https://github.com/codeready-toolchain/host-operator/pull/298
=> chore: verify that UserSignup has corresponding state label values set

make/clean.mk, make/test.mk, testsupport/init.go
Verify that the creation of new SA with limited Role & ClusterRole when joining clusters works.
It also creates a new SA for the e2e tests and uses the `add-cluster.sh` script also for copying the token and creating separated `ToolchainCluster` resource.
Relies on changes from: https://github.com/codeready-toolchain/toolchain-common/pull/133
=> chore: verify creation of new SA when joining a cluster

test/e2e/user_workloads_test.go, wait/member.go
Our Idler test is currently flaky because pod (or pod controller) creation fails from time to time due to this upstream issue: https://github.com/kubernetes/kubernetes/issues/67761
In this PR we create pods in a loop until success.
=> Create pods in a loop until success

test/e2e/usersignup_test.go, testsupport/conditions.go, wait/host.go
verify waiting list for UserSignup, which means that the controller will approve the oldest unapproved UserSignup when there is a member cluster with free capacity
paired with: https://github.com/codeready-toolchain/host-operator/pull/306
=> chore: verify waiting list for UserSignup

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/registration_service_test.go, testsupport/conditions.go, testsupport/toolchain_status_assertions.go, testsupport/user_assertions.go, wait/member.go
Verifies that MemberStatus controller retrieves the console url and stores it in MemberStatus CR
Paired with: https://github.com/codeready-toolchain/member-operator/pull/213
=> chore: verify that Console & Che routes are added to MemberStatus

test/e2e/e2e_test.go, test/e2e/user_management_test.go, wait/metrics_test.go
Rename user_signups_provisioned_total to user_signups_approved_total since approved doesn't necessarily mean provisioned.
Also fix metrics_test.go.
=> chore: Rename user_signups_provisioned_total to user_signups_approved_total

test/e2e/e2e_test.go
=> fix: ensure auto-approval is disabled when starting TestE2EFlow

tiers/checks.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/318
=> Tiers: 15Gi for storage & rbac-edit role for -dev and -stage

test/e2e/registration_service_test.go
This is just for improving error messaging in reg-service tests.
It's paired with https://github.com/codeready-toolchain/registration-service/pull/141 but will fail until https://github.com/codeready-toolchain/host-operator/pull/320 is merged.
=> Improve error messaging

test/e2e/registration_service_test.go
E2e tests for https://github.com/codeready-toolchain/registration-service/pull/144
Also I refactored the reg-service tests a bit to get rid of a lot of code duplication.
=> e2e for usersignup reactivation in reg-service

make/test.mk, openshift-ci/Dockerfile.member.webhook.deploy
This PR adds a support for member-operator-webhook image so it can be built as part of openshift-ci setup
used here: https://github.com/openshift/release/pull/13872
=> chore: support member-operator-webhook image

testsupport/tier_setup.go, tiers/templaterefs.go, wait/host.go
improve waiting for updated tier - the current wait checks the template refs incorrectly - we should just check the suffix that refers to the commit sha.
=> fix: improve waiting for updated tier

wait/awaitility.go, wait/metrics.go
When running e2e tests locally, it happened a few times that the e2e tests reached the 1sec limit when getting the metrics endpoint. 
So I made it way longer - I know that it's maybe too much, but it doesn't harm :-)
=> fix: prolong timeout when reaching metrics endpoint

make/test.mk, testsupport/user_setup.go
in the last few CI runs, there were failures when waiting for updated NSTemplateTier `basic` resource: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/codeready-toolchain_member-operator/222/pull-ci-codeready-toolchain-member-operator-master-e2e/1332392569098735616/build-log.txt
My best guess is that the setup logic waits for the host-operator being deployed and then it applies the dummy basic resource. But if the setup logic is too slow, then it updates the already created `basic` tier to the dummy version that cannot be then "fixed" by the operator logic.
To fix this, I deploy the `NSTemplateTier` CRD and create the dummy `basic` tier before deploying the host-operator
paired with: https://github.com/codeready-toolchain/host-operator/pull/327
=> fix: create dummy basic tier before deploying the host operator

make/clean.mk, make/test.mk, test/e2e/e2e_test.go, test/e2e/user_workloads_test.go, wait/awaitility.go, wait/member.go
Verifies that all objects from the webhook template are properly deployed with the expected values
Checks that all pods that are created in the users' namespaces have the lower priority class set as well as the priority value. Pods that are created outside the users' namespaces are not touched by the webhook.
Paired with: https://github.com/codeready-toolchain/member-operator/pull/223
=> feat: verify webhook that sets lower priority to users' pods

test/e2e/nstemplatetier_test.go, test/e2e/user_management_test.go, tiers/checks.go, wait/host.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/329
- Updates the nstemplatetier tests to include the new `basic-no-deactivation` tier.
- Adds a deactivation test to check that users in tiers without deactivation are indeed not deactivated.
=> Update tests for basic-no-deactivation tier

make/test.mk, wait/member.go
* print the member-operator-webhook log when tests fail
* print info while checking resources
* wait until the webhook deployment is ready
=> fix: improve logging & checks of member operator webhook

make/test.mk
previous wrong image name:
```
registry.svc.ci.openshift.org/codeready-toolchain/member-operator-webhook-v0.1:member-operator-webhook
```
the new correct one
```
registry.svc.ci.openshift.org/codeready-toolchain/member-operator-v0.1:member-operator-webhook
```
=> fix: use correct member-operator-webhook image name built from master

testsupport/metrics.go, wait/host.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/352
The above PR updates the logic related to deleting user accounts to verify the deletion is completed before continuing with the MasterUserRecord deletion. As a side effect the MUR deletion can take longer. The `WaitForUserSignupsBeingDeleted` test helper function waits for UserSignups to be deleted before initializing metrics values for testing, however, UserSignups can currently be deleted whilst MURs are still being delete. This caused the MUR count that was captured at the beginning of the test to be inaccurate because some MURs were still being deleted.
This PR updates the e2e tests to also wait for the MURs to be deleted as a fix for the problem. It renames the `WaitForUserSignupsBeingDeleted` function to be …
=> Wait for MURs to be deleted before gathering metrics

tiers/checks.go
e2e tests for https://github.com/codeready-toolchain/host-operator/pull/358
Verifies the network policies are correctly configured for each tier's namespace grouping.
=> Update network policy tests for user namespace networking

test/e2e/registration_service_test.go
The format expected from the woopra-domain and segment-write-key should be string instead of JSON.
See the discussion: https://issues.redhat.com/browse/CRT-753
Related PR: codeready-toolchain/registration-service#166
This PR updates the tests to expect string format instead of JSON.
=> changing woopra-domain and segment-write-key to return strings

test/e2e/registration_service_test.go, testsupport/init.go
Added e2e test for https://github.com/codeready-toolchain/registration-service/pull/168
Fixes https://issues.redhat.com/browse/CRT-883
This PR also includes an increase to the timeout of client requests to the host API, to allow a greater threshold when running in CRC.
Signed-off-by: Shane Bryzak <shane@localhost.localdomain>
=> Added test to ensure users may not sign up with phone number already in use

setup/README.adoc
This PR:
* Adds `member-operator-webhook` quay repo to be set `public` into `Prereqs` instructions.
* Makes the quay repo visibility section a little bit more readable.
=> Add member-operator-webhook quay repo to be set public into Prereqs instructions

setup/README.adoc
The `--active` flag can be used to control the number of users that have the template resources created in one of their namespaces.
=> Update README.adoc replacing resource-rate with active users flag

test/e2e/registration_service_test.go
e2e test updated to check apiEndpoint is returned by Registration Service's signup service (GET /api/v1/signup) for an approved user.
wrt fix: https://issues.redhat.com/browse/CRT-971
changes in registration service : https://github.com/codeready-toolchain/registration-service/pull/176
=> e2e test updated to check apiEndpoint is returned by Registration Service's signup service

make/dev.mk, make/test.mk
Because we don't need to deploy two member operators in one cluster when either setting up the cluster for performance tests or just for dev purposes, I've added make targets to be able to define how many members should be deployed.
=> feat: add posibility to deploy dev env without second member

go.mod, go.sum, test/e2e/base_user_test.go, test/e2e/nstemplatetier_test.go, test/e2e/registration_service_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, testsupport/metrics.go, testsupport/user_assertions.go, testsupport/user_setup.go, testsupport/wait/awaitility.go, testsupport/wait/host.go
E2E Tests for https://github.com/codeready-toolchain/host-operator/pull/401
Checks the new `sandbox_users_per_activations ` metric when users are deactivated and reactivated multiple times
=> metrics: add field to store metrics in ToolchainStatus

testsupport/user_setup.go
avoids starting the test with a user having 2 activations, and some
weird effects on the metrics, such as
```
$ oc get toolchainstatus/toolchain-status -o jsonpath='{.status.metrics} | jq -r
{
"usersPerActivation": {
"1": -1
"2": 1
}
}
$ curl -X GET https://$(oc get route/host-operator-metrics -o json | jq -r '.status.ingress[0].host')/metrics -k -s | grep sandbox_users_per_activations"
sandbox_users_per_activations{activations="1"} -1
sandbox_users_per_activations{activations="2"} 1
```
Existing tests themselves are not affected, since they measure a delta
between the initial metrics/counters and their value after something
changed (user deactivation/reactivation, etc.)
=> fix usersignup setup

go.mod, go.sum, setup/configuration/configuration.go, setup/idlers/update_idler.go, setup/test/fakeclient.go, setup/users/create_users.go, setup/users/create_users_test.go, test/e2e/base_user_test.go, test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, test/e2e/registration_service_test.go, test/e2e/toolchaincluster_test.go, test/e2e/user_management_test.go, test/e2e/user_workloads_test.go, test/e2e/usersignup_test.go, test/perf/perf_test.go, testsupport/conditions.go, testsupport/init.go, testsupport/tier_setup.go, testsupport/tiers/checks.go, testsupport/tiers/nstemplateset.go, testsupport/tiers/templaterefs.go, testsupport/toolchain_status_assertions.go, testsupport/user_assertions.go, testsupport/user_setup.go, testsupport/wait/awaitility.go, testsupport/wait/host.go, testsupport/wait/member.go
result of codeready-toolchain/api#237
* small changes in go.mod so we can use the new controller-tools 0.4.1 together with client-go 0.18.3
* update all imports to api repo/types
related PRs, but NOT paired:
https://github.com/codeready-toolchain/member-operator/pull/254
https://github.com/codeready-toolchain/host-operator/pull/441
https://github.com/codeready-toolchain/registration-service/pull/191
=> chore: update api with new format & kubebuilder version

testsupport/tiers/checks.go
Tests for increase idler timeout to 12 hours
Related PR: https://github.com/codeready-toolchain/host-operator/pull/454
=> Update tier check for updated idler timeout

test/e2e/e2e_test.go, testsupport/wait/member.go
Verifies the memberoperatorconfigs for each member cluster.
Related PR: https://github.com/codeready-toolchain/member-operator/pull/265
=> Verify memberoperatorconfigs

test/e2e/user_management_test.go, testsupport/signup_request.go
Minor fix to modify `SignupRequest` to use the awaitility `Cleanup()` function.
=> Use awaitility Cleanup() instead

test/e2e/user_management_test.go
user can be provided to any member when automatic approval is enabled and no target cluster is required
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/codeready-toolchain_member-operator/270/pull-ci-codeready-toolchain-member-operator-master-e2e/1407954437116268544/build-log.txt
=> fix(flaky): user can be provisioned to any member with automatic approval

testsupport/wait/member.go
Tests for https://github.com/codeready-toolchain/member-operator/pull/270
=> Use priority between 0 and -10 to fit the default threshold in ClusterAutoscaler

testsupport/wait/member.go
Tests for https://github.com/codeready-toolchain/member-operator/pull/271
=> Autoscaler buffer priority should be higher than autoscaler threshold

testsupport/wait/awaitility.go
The cleanup sometimes takes a long time to finish and there is a lot of messaging around that. Originally, I wanted to clean it in parallel, but when I tried it the client failed with:
```
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 2056 [running]:
runtime.throw(0x166d513, 0x15)
/home/mjobanek/go/go/src/runtime/panic.go:1117 +0x72 fp=0xc0009d6ee0 sp=0xc0009d6eb0 pc=0x43a2b2
runtime.mapassign(0x14ce6e0, 0xc00031d3b0, 0xc000b4e8a0, 0xc000495320)
/home/mjobanek/go/go/src/runtime/map.go:676 +0x591 fp=0xc0009d6f60 sp=0xc0009d6ee0 pc=0x411f51
reflect.mapassign(0x14ce6e0, 0xc00031d3b0, 0xc000b4e8a0, 0xc000b4e8b0)
/home/mjobanek/go/go/src/runtime/map.go:1328 +0x3f fp=0xc0009d6f90 sp=0xc0009d6f60 pc=0x46d0ff …
```
=> fix: improve cleanup messaging

scripts/manage-operator.sh
this disables e2e pairing with more than one repo
paired with: 
https://github.com/codeready-toolchain/member-operator/pull/279
https://github.com/codeready-toolchain/host-operator/pull/483
so it should fail in the pairing process
=> disable multiple pairing

make/test.mk
only use the `toolchain-member2-${DATE_SUFFIX}` when the
env var is not already defined.
=> build: use 'MEMBER_NS_2' env var when it's defined

deploy/member2-operator/dev/member-operator-config-map.yaml, deploy/member2-operator/e2e-tests/hack.yaml, deploy/member2-operator/e2e-tests/member-operator-config-map.yaml, make/test.mk
Removes the previous hack that was in place temporarily until the autoscaler and webhook deployment was moved to the member operator controller.
Related PR: https://github.com/codeready-toolchain/member-operator/pull/281
=> Remove workaround for webhook deploy

test/e2e/nstemplatetier_test.go, testsupport/tiers/checks.go
Updates the tests to include the new baseextendedidling tier that has idling timeout set to 24 hours.
Related PR: https://github.com/codeready-toolchain/host-operator/pull/486
=> Tests for new baseextendedidling tier

setup/operators/operators.go
It looks like the subscriptions now have an identifier appended so the setup tool needs to update to look for a prefix instead of an exact match
=> Lookup subscription using prefix

setup/cmd/root.go, setup/operators/installtemplates/kiali.yaml, setup/operators/installtemplates/rhoas.yaml, setup/operators/installtemplates/sbo.yaml, setup/operators/operators.go
SBO and other operators take a long time to install using the setup tool because it's trying to install from older versions. It can also cause problems when just retrying the setup tool so just update to the newer versions.
=> Update operator versions

deploy/host-operator/e2e-tests/toolchainconfig.yaml
The go routine that checks the health of host cluster is created when the operator is started: https://github.com/codeready-toolchain/toolchain-common/blob/master/controllers/toolchaincluster/healthchecker.go#L33-L35 - at that time it uses the default value (which is 10s) because the MemberOperatorConfig is still not propagated from host (5s). 
let's drop the shorter period and use only the default one
=> fix: use default health check period

test/e2e/e2e_test.go, test/e2e/user_workloads_test.go, testsupport/wait/member.go
A couple of the tests don't specify a target cluster when creating a new UserSignup so the UserAccount and other member cluster resources could be on member1 or member2 but the tests only perform assertions on a particular member cluster which leads to test flakiness.
This PR sets the target cluster to the cluster used for the assertions but we can probably make this a little more intuitive and reduce/eliminate future test flakiness related to this type of problem.
=> Quick fix for a couple flaky tests

test/e2e/nstemplatetier_test.go, testsupport/wait/member.go
When waiting fails, then print also the content of the UserAccount as well as the NSTempalteSet
is paired with: https://github.com/codeready-toolchain/member-operator/pull/292
=> fix: add better logging to fix UserAccount in updating state

test/e2e/user_management_test.go, testsupport/conditions.go
Tests for https://github.com/codeready-toolchain/host-operator/pull/504
Fixes https://issues.redhat.com/browse/CRT-1219
=> Confirm notification won't be created when user has no email address

README.adoc, deploy/host-operator/dev/host-operator-config-map.yaml, deploy/host-operator/e2e-tests/host-operator-config-map.yaml
Related Issue: https://issues.redhat.com/browse/CRT-1176
Removes the old host operator config map and updates the README.
=> Remove old config files and update README

make/resources/default-network-policies.yaml, make/test.mk
this is only needed if the cluster in use was configured
with the `sandbox-cli setup` command. In this case, the
`name=openshift-openshift-operator-lifecycle-manager` label
is needed to successfully deploy the operators.
=> test: add label on OLM namespace

testsupport/tiers/checks.go
verifies that the expected Role & RoleBindings resources are created
paired with: https://github.com/codeready-toolchain/host-operator/pull/510
=> chore: verify view & exec perms for crtadmins

go.mod, go.sum, setup/templates/template.go, testsupport/wait/awaitility.go
see also https://github.com/codeready-toolchain/toolchain-common/pull/210 and  https://github.com/codeready-toolchain/member-operator/pull/297
=> refactor: direct use 'client.Object' instead of 'meta.Accessor()'

make/resources/default-network-policies.yaml
While using `make dev-deploy-e2e`, I noticed the error message
```
Already on project "toolchain-host-operator" on server "https://api.dwo-2021-09-24.devcluster.openshift.com:6443".
namespace/toolchain-host-operator labeled
adding network policies in toolchain-host-operator namespace
error: failed to read input object (not a Template?): unable to decode "/home/amisevsk/git/toolchain-e2e/make/resources/default-network-policies.yaml": v1.Template.Objects: []runtime.RawExtension: decode slice: expect [ or n, but found {, error found in #10 byte of ...|objects":{"apiVersio|..., bigger context ...|a":{"name":"default-network-policies"},"objects":{"apiVersion":"networking.k8s.io/v1","kind":"Networ|...
error: no objects passed to apply
make[2]: [make/test.mk:224: create-project] Error 1 …
```
=> Fix malformed yaml template for network policies

testsupport/signup_request.go
IIRC http.Transport reuses connections by default in go, so it could have happened that it reused some old connection that was closed by the server. In that case, the client could get the EOF error. 
by setting `req.Close = true` we should prevent from reusing the connection.
=> fix: don't reuse connections

test/e2e/user_management_test.go
=> use 't' instead of 's.T()' in substests

.github/workflows/ci-build.yml, make/test.mk
There is no point in having the code-coverage for e2e tests and the CodeCov "warning" comments in the PR reviews are really annoying and make the review harder.
=> feat: drop codecov to make the PR reviews easier

make/dev.mk, make/test.mk
Have ever been struggling with figuring out what was going on with your e2e test? Have you ever wanted to run it from your IDE or debug the test code? 
This should make it easier. The target prints out a set of `os.Setenv(...,...)` calls - if you copy it and paste it at the very beginning of your test/suite, then you should be able to run/debug the test directly from the IDE.
=> feat: add print-local-debug-info target

deploy/host-operator/appstudio-e2e/secrets.yaml, deploy/host-operator/appstudio-e2e/toolchainconfig.yaml, make/appstudio.mk, make/clean.mk, make/dev.mk, make/test.mk
introduce: 
* appstudio-e2e environment config YAML files
* appstudio-e2e-deploy-latest target that deploys the latest toolchain operators in appstudio-e2e environment
* deletion of registration-service pods after the `ToolchainConfig` CR is created - this is for the case when we would run for example `appstudio-dev-deploy-latest` & `appstudio-e2e-deploy-latest` after each other, without cleaning the namespaces.
refactoring:
* move all appstudio related targets to `appstudio.mk`
* a few changes in the `clean.mk` to make it more flexible and reusable 
Fixes:
* the way we get the registration page URL - the `$(eval ROUTE = $(shell ` is evaluated at the very beginning when the target was called, so if it wasn't available at that time, then the echo would print only `Access the Landing Page …
=> feat: add appstudio-e2e-deploy-latest target

test/e2e/e2e_test.go, test/e2e/proxy_test.go, test/e2e/user_management_test.go, testsupport/wait/host.go, testsupport/wait/member.go
GetMasterUserRecord:
* returns an error when the MUR is not found
* accepts only name (as this is the only case when it's being used)
* it doesn't print any diff as it's not needed
=> fix: GetMasterUserRecord returns err when not found (without diff print)

test/e2e/nstemplatetier_test.go, testsupport/tiers/nstemplateset.go, testsupport/wait/host.go
these small changes should shorten the test execution time.
* run object checks in parallel
* verify the TierTemplate resources only during NSTemplateTier tests
=> feat: run object checks in parallel

make/dev.mk
our makefile targets will be executed from https://github.com/redhat-appstudio/infra-deployments and since the targets print clean command at the end of the execution, it would be good to customize it to avoid any confusion.
The usage:
```
make -C ${TOOLCHAIN_E2E_TEMP_DIR} appstudio-e2e-deploy-latest SHOW_CLEAN_COMMAND="make -C ${TOOLCHAIN_E2E_TEMP_DIR} appstudio-cleanup"
```
=> feat: add SHOW_CLEAN_COMMAND var

test/e2e/registration_service_test.go, testsupport/init.go
e2e test for https://issues.redhat.com/browse/CRT-1396
related PR: https://github.com/codeready-toolchain/registration-service/pull/242
=> check proxyURL is populated in signup response

testsupport/cleanup/clean.go, testsupport/signup_request.go, testsupport/wait/awaitility.go
This PR refactors and improves the cleanup of the resources (that is performed at the end of each test) so it is executed in parallel - this change decreases the overall test execution by a few minutes.
=> feat: clean objects in parallel

testsupport/init.go, testsupport/wait/awaitility.go, testsupport/wait/host.go, testsupport/wait/member.go
It makes sure that the initialization of the awaitilities is executed only once. It decreases the overall test execution by 4-5 minutes.
=> feat: run initialization of awaitilities only once

go.mod, go.sum, test/e2e/nstemplatetier_test.go, test/e2e/space_test.go, testsupport/space.go, testsupport/tiers/checks.go, testsupport/tiers/templaterefs.go, testsupport/util.go
This PR extracts some Space-related functions and makes them a bit more generic so they can be easily used in the migration tests
=> refactor: extract some functions to make it available outside of the e2e package

make/test.mk, test/migration/setup/setup_migration_test.go, test/migration/setup_runner.go, test/migration/verify/verify_migration_test.go
This PR introduces migration infra & tests. It covers that the operator updates don't break anything and don't cause deletion of the existing accounts.
I called them "migration tests", but we could also call them "update tests" - I can change it if needed.
There are 3 significant changes:
1. a few modifications/refactoring in `test.mk` so:
- by default the `test-e2e` target will:
* setup the projects
* deploy the latest version of our operators
* run "before migration" tests which will provision UserSignups and Spaces
* reinstall the operators to use the one from PR
* run "after migration"tests which will check that nothing is broken nor deleted
* run the standard set of tests
- there is a new target `test-e2e-without-migration` which will skip the migration part. That means that it won't …
=> feat: introduce operator update tests

test/e2e/nstemplatetier_test.go, test/e2e/space_test.go, test/e2e/spacebinding_test.go, test/migration/setup_runner.go, testsupport/space.go, testsupport/wait/host.go
The PR brings a few more helper functions for easy creation and verification of Space resources.
It also replaces the current usages with the new unified functions.
There is maybe one unused criterion function - I'll use it in the next PR - it was just easier to include this here as well :-)
=> refactoring: unify space functions

setup/metrics/gather.go, setup/metrics/queries/query.go
Adding memory query for kube-apiserver since there was an increase in its memory usage that went undetected after GitOps Primer operator was onboarded.
Sample of results with the new query included:
```
📈 Results 📉
Average Idler Update Time: 1.31 s
Average Time Per User: 5.00 s
Average openshift-kube-apiserver: 12030.16 MB <- new query
Max openshift-kube-apiserver: 12030.16 MB
Average Cluster CPU Utilisation: 16.72 %
Max Cluster CPU Utilisation: 16.72 %
Average Cluster Memory Utilisation: 37.13 %
Max Cluster Memory Utilisation: 37.13 %
Average Node Memory Usage: 38.37 %
Max Node Memory Usage: 38.37 %
Average etcd Instance Memory Usage: 586.21 MB
Max etcd Instance Memory Usage: 586.21 MB
Average olm-operator CPU Usage: 0.0025
Max olm-operator CPU Usage: 0.0025
Average olm-operator Memory …
```
=> Add query for kube-apiserver

go.mod, go.sum, testsupport/user_assertions.go, testsupport/wait/member.go
verify that `User` & `UserAccount` resources have email annotation + a few refactoring changes to make the function names consistent
paired with https://github.com/codeready-toolchain/member-operator/pull/340
=> verify that User resource has email annotation

setup/cmd/root.go
Allows skipping confirmation prompts when option is explicitly set to `false`.
```
go run setup/main.go --interactive=false --username zorro --users <number_of_users_left_to_create> --default <number_of_users_left_to_create> --custom <number_of_users_left_to_create>
```
Used in dev sandbox performance testing when provisioning many users with different user workload templates.
=> chore: Add interactive cli option

test/e2e/space_cleanup_test.go, testsupport/space.go
I merged the two cleanup tests which makes the flow much better - no idea why I didn't realize it before :man_shrugging:  :man_facepalming: 
https://github.com/codeready-toolchain/toolchain-e2e/pull/479#discussion_r812968732
=> refactor: improve the flow of the space_cleanup_test.go

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/registration_service_test.go, testsupport/user_assertions.go, testsupport/wait/member.go
Fixes e2e tests to work with new UserID encoding rules.
https://github.com/codeready-toolchain/member-operator/pull/342
=> Fix e2e tests with userID encoding change

test/e2e/toolchainstatus_test.go, test/metrics/metrics_test.go, testsupport/metrics.go
capture metric baseline values from both members, otherwise, it cannot calculate the delta properly which can lead to a flaky test
=> fix: capture metric baseline values from both members

dev_install.adoc, make/dev.mk, make/test.mk
When the operators are installed in an OSD cluster then we need to use let's encrypt certificates for registering the operators
=> feat: support OSD in dev deployment

test/e2e/space_cleanup_test.go, testsupport/wait/host.go
The `TestSpaceAndSpaceBindingCleanup` test becomes flaky after the changes from https://github.com/codeready-toolchain/host-operator/pull/595 are in place. These changes ensure the tests pass with and without the changes from that PR.
Summary of Changes:
1. The deletion of the MUR happens much faster with the changes from https://github.com/codeready-toolchain/host-operator/pull/595 and I suspect the UserSignup is recreating it right away so deleting the MUR directly and then verifying the SpaceBinding is deleted becomes flaky so to work around that we can instead deactivate the UserSignup to ensure the MUR stays deleted and then we can verify the SpaceBinding is deleted.
2. The `for Spaces` sub-tests fail because the previous test executes in under 30 seconds. To work around this I …
=> Fix flaky test

test/e2e/e2e_test.go, test/e2e/space_autocompletion_test.go, test/e2e/usersignup_test.go, testsupport/wait/host.go
it has happened that the test took some value from ToolchianStatus, but the values weren't up-to-date with the current state of the cluster. 
So we need to wait until the ToolchainStatus is updated
=> fix(flaky-tests): wait until ToolchainStatus is updated

make/test.mk, testsupport/wait/awaitility.go
install member operators first and then the host
also, increase the timeout
This could help with the flaky second member installation - hopefully
=> fix: install members first

setup/README.adoc, setup/operators/installtemplates/devworkspace-operator.yaml, setup/operators/installtemplates/gitops-primer-template.yaml, setup/operators/installtemplates/kiali.yaml, setup/operators/installtemplates/rhoas.yaml, setup/operators/installtemplates/rhoda.yaml, setup/operators/installtemplates/sbo.yaml, setup/operators/installtemplates/serverless-operator.yaml, setup/operators/operators.go
- Installs the rhoda (DBaaS) operator which will automatically install the mongo, crunch and cockroach operators.
- Updates the starting versions for some of the other operators to speed up installation process
- Mention installing latest OCP 4.10.x in README
=> Install rhoda and update other operator versions

make/dev.mk, make/test.mk, testsupport/wait/awaitility.go
this PR brings two improvements to get rid of reg-service flakiness:
* it doesn't force-restart the reg-service pods if it's part of e2e test execution
* lists all pods of the deployment the test is waiting for and checks that:
* the number of pod matches the expected number of replicase
* none of the pod is being deleted
* all pods are ready
=> fix: get rid of reg-service flakiness

make/test.mk
this is supposed to fix the webhook flaky tests. We need to register the ToolchainCluster right after the host installation so it can immediately distribute the `MemberOperatorConfig` in both members so the second member can load the config right after starting and not deploy the webhook.
=> fix: register ToolchainCluster after host installation

make/test.mk, test/e2e/parallel/space_cleanup_test.go, test/e2e/parallel/space_test.go, test/e2e/space_autocompletion_test.go, testsupport/signup_request.go, testsupport/spacebinding.go
* creates a new directory called `parallel` which will contain tests that are executed in parallel
* moves `space_cleanup_test.go` and `space_test.go` in the directory (other tests will be moved in the following PRs)
* marks the test to be runnable in parallel
* adds configuration param to the `go test` command to configure the parallelism
* when the parallel tests are being executed, then check all usernames for any duplications
=> feat: introduce test parallelism

testsupport/tiers/checks.go
Update role checks for AppStudio users to create, delete, get, list, watch RegisteredClusters
Paired with https://github.com/codeready-toolchain/host-operator/pull/631
Signed-off-by: Robin Y Bobbitt <rbobbitt@redhat.com>
=> update appstudio user actions role check for registeredclusters

test/e2e/parallel/registration_service_test.go, test/e2e/user_management_test.go, testsupport/wait/host.go
This is another PR in the effort of running e2e tests in parallel. This time it is for `registration_service_test.go`
Changes:
* moved `registration_service_test.go` to `parallel` dir
* transformed the test from suites to normal standalone tests (the testing framework doesn't have full support for running suites in parallel https://github.com/stretchr/testify/issues/187)
* introduce & use `WaitAndVerifyThatUserSignupIsNotCreated` to verify that a UserSignup is not created
=> feat: run registration_service_test in parallel

test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/proxy_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/migration/verify/verify_migration_test.go, testsupport/deactivation.go, testsupport/signup_request.go, testsupport/tiers/tier_setup.go, testsupport/user_assertions.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/637
- tests that user deactivation works with both UserTier and NSTemplateTier (NSTemplateTier deactivation test will be removed after UserTier migration is complete)
- updates Verify functions to accept both `userTierName` and `spaceTierName` where `userTierName` corresponds to the expected MUR TierName and `spaceTierName` corresponds to  the expected Space TierName
- split `MoveUserToTier` helper function into `MoveSpaceToTier` and `MoveMURToTier`
=> Test deactivation controller with UserTiers

setup/metrics/gather.go
Hello, we are using the metrics pkg as an dependency for load testing AppStudio , well we just needed one empty metrics instance that we will add the workloads later from our script PTAL .
=> Chore: Add empty metrics instance for appstudio

make/test.mk, setup/README.adoc
- Adds a `test-e2e-local-without-migration` make target that is a convenient way to run the tests locally without migration tests
- Minor fix to the setup README
=> Test local skip migration and fix setup README

go.mod, go.sum, test/e2e/e2e_test.go, test/e2e/nstemplatetier_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/space_test.go, test/e2e/proxy_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/migration/setup_runner.go, test/migration/verify/verify_migration_test.go, testsupport/deactivation.go, testsupport/signup_request.go, testsupport/tiers/tier_setup.go, testsupport/user_assertions.go, testsupport/wait/diff.go, testsupport/wait/host.go
Related PR: https://github.com/codeready-toolchain/host-operator/pull/642
- Adds a temporary test for user tier migration
- Temporary updates to general migration tests to pass with user tier migration
- Remove usages of ChangeTierRequests
=> Test migration to user tiers

test/e2e/parallel/space_test.go, testsupport/wait/diff_test.go, testsupport/wait/member.go
avoid flaky case where namespace already has the
'toolchain.dev.openshift.com/last-applied-space-roles' annotation but
its associated NSTemplateSet was retrieved too early and did not have
the corresponding space roles
=> test: wait until NSTemplateSet has expected space roles

testsupport/tiers/checks.go
This PR is paired with: https://github.com/codeready-toolchain/host-operator/pull/661
=> test: Allow appstudio users to create Environment APIs

testsupport/tiers/checks.go
This PR is paired with https://github.com/codeready-toolchain/host-operator/pull/664
=> e2e test: Allow appstudio users to  create hacbs APIs

testsupport/tiers/checks.go
needed by AppStudio Proxy to obtain a token for a ServiceAccount
=> test(appstudio/proxy): permissions to create TokenRequest API

testsupport/wait/member.go
This is a follow-up of #597 in which the assertion needed to be
permissive enough to accomodate with the migration tests.
Now that the new admission webhook for CheClusters has been deployed,
the assertion can be strict.
Fixes https://issues.redhat.com/browse/CRT-1586
=> test: more strict assertion on webhook configuration

setup/cmd/root.go, setup/metrics/queries/query.go
- Use `container_memory_working_set_bytes` because `container_memory_usage_bytes` includes the usage of all kinds of memory (including cache that can be evicted at any time) while container_memory_working_set_bytes  only includes the memory that cannot be evicted. So it's a better representation of the actual memory usage.
- Continue gathering metrics for 15m after provisioning users because memory continues to grow for some time after provisioning is completed
=> Use working set memory metric for perf testing

test/e2e/parallel/registration_service_test.go
To avoid errors like this:
```
registration_service_test.go:567: 
Error Trace:	registration_service_test.go:567
Operation cannot be fulfilled on usersignups.toolchain.dev.openshift.com "testuser-1dd6a16d-337a-42a7-9fcc-c3026c806192": the object has been modified; please apply your changes to the latest version and try again
Test:       	TestPhoneVerification
```
=> Fix flaky registration service tests

setup/resources/user-workloads.yaml
Imagestream doesn't exists which leads to generation lot of events w.r.t. buildconfig.
=> Update imagestream in default user-workloads

make/test.mk
Dump operator logs to files during openshift ci.
The logs will be saved in the in the `artifacts` folder with the following naming convention `${DEPLOYMENT_NAME}.log`.
Example job with logs saved to files:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/635/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1602062639536541696/artifacts/e2e/test/artifacts/
Jira ticket: [CRT-1469](https://issues.redhat.com/browse/CRT-1469)
=> Store host and member operator logs in artifacts directory on OpenShift CI

test/e2e/usersignup_test.go
This PR fixes this e2e failure:
```
TestRunUserSignupIntegrationTest/TestCapacityManagementWithManualApproval/set_low_max_number_of_spaces_and_expect_that_user_won't_be_provisioned_even_when_is_approved_manually
signup_request.go:262: 
Error Trace:	/go/src/github.com/codeready-toolchain/toolchain-e2e/test/e2e/signup_request.go:262
/go/src/github.com/codeready-toolchain/toolchain-e2e/test/e2e/usersignup_test.go:332
timed out waiting for the condition
Test:       	TestRunUserSignupIntegrationTest/TestCapacityManagementWithManualApproval/set_low_max_number_of_spaces_and_expect_that_user_won't_be_provisioned_even_when_is_approved_manually
.......
--- FAIL: TestRunUserSignupIntegrationTest (190.16s)
--- PASS: …
```
=> invert test user signup manual approval scenarios

make/test.mk
The reason is that we have two member instances and the second instance overrides the log of the first one
=> fix: reflect the namespace the logs are pulled from

test/e2e/space_autocompletion_test.go
This PR fixes failure:
```
--- FAIL: TestAutomaticClusterAssignment (278.00s)
--- FAIL: TestAutomaticClusterAssignment/set_low_max_number_of_spaces_and_expect_that_space_won't_be_provisioned_but_added_on_waiting_list (248.01s)
--- FAIL: TestAutomaticClusterAssignment/set_low_max_number_of_spaces_and_expect_that_space_won't_be_provisioned_but_added_on_waiting_list/increment_the_max_number_of_spaces_and_expect_that_first_space_will_be_provisioned. (246.06s)
FAIL
FAIL	github.com/codeready-toolchain/toolchain-e2e/test/e2e	1087.098s
```
link to failed build:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/636/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1604807795008344064
- invert set low capacity threshold with set low max number of …
=> Fix test automatic cluster assignment

test/e2e/toolchaincluster_test.go
create `toolchainCluster` resource in `await.Namespace` with `otherAwait.Type` .
In the scenario where `await.Namespace` is `toolchain-host-ns`, the type label for the `toolchainCluster` resource should be `otherAwait.Type` (so `member` in this case)
=> small fix on creating the toolchainCluster with expected type label

testsupport/tiers/checks.go
test for https://github.com/codeready-toolchain/host-operator/pull/731
=> fix: resource name should be in plural form

testsupport/tiers/checks.go
Pipeline serviceAccount is used for running tekton pipelines and users should be able to attach secrets for container and git repositories.
=> appstudio: Allow manage pipeline serviceaccount

testsupport/tiers/checks.go
Pipeline Service keeps the latest 10 PipelineRuns, so the quota is increased to 12 to allow for 2 PipelineRuns to be created before the pruner makes more space for additional PipelineRuns. Storage size is increased to 50Gi.
See https://github.com/codeready-toolchain/host-operator/pull/737
Signed-off-by: Romain Arnaud <rarnaud@redhat.com>
=> Increase PVC size and count for AppStudio

test/e2e/proxy_test.go
Some e2e jobs where failing while checking the match between `Workspace.ObjectMeta` fields and `Space.ObjectMeta` fields:
```
host.go:1640: waiting for Space 'bus' with matching criteria
=== RUN   TestSpaceLister/bicycle_gets_workspaces/can_get_car_workspace
host.go:1640: waiting for Space 'car' with matching criteria
proxy_test.go:740: 
Error Trace:	/tmp/toolchain-e2e/test/e2e/proxy_test.go:740
/tmp/toolchain-e2e/test/e2e/proxy_test.go:471
Error:      	Not equal: 
expected: "75067"
actual  : "74984"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-75067
+74984
Test:       	TestSpaceLister/bicycle_gets_workspaces/can_get_car_workspace
```
Jira task: https://issues.redhat.com/browse/ASC-296
=> update proxy test to verify NotEmpty fields in Workspace objects

testsupport/tiers/checks.go
This PR removes write access to GitOpsDeployment from users of Stonesoup, as the ability to create/modify a GitOpsDeployment would allow the user to bypass per-user security boundaries.
Corresponding host operator PR: https://github.com/codeready-toolchain/host-operator/pull/749
JIRA: [GITOPSRVCE-427](https://issues.redhat.com/browse/GITOPSRVCE-427)
=> Allow only read access to GitOpsDeployments

testsupport/tiers/checks.go
Add create permission for `SelfSubjectAccessReview` to allow for RBAC checks in UI.
Host operator PR: https://github.com/codeready-toolchain/host-operator/pull/766
=> Allow create access for SelfSubjectAccessReview

testsupport/tiers/checks.go
This reverts commit 17923304f8680998f0cf6b7c797c394dfb87b006.
Host operator PR https://github.com/codeready-toolchain/host-operator/pull/769
=> Revert PR #681

test/e2e/proxy_test.go, testsupport/proxyplugin.go, testsupport/wait/host.go
paired with https://github.com/codeready-toolchain/registration-service/pull/311
=> PLNSRVCE-1166: add proxy plugin e2e test accessing the console route

openshift-ci/Dockerfile.tools
Upgrade go version in openshift-ci dockerfile so that we can probably avoid the issue in this PR when upgrading to Golang 1.19.7 : https://github.com/codeready-toolchain/toolchain-e2e/pull/694
=> upgrade golang version go1.18.8 in openshift-ci

deploy/host-operator/appstudio-dev/toolchainconfig.yaml, deploy/host-operator/appstudio-e2e/toolchainconfig.yaml
dev clusters are often quite tight on resources, increase the capacity threshold to 90
=> Increase resource threshold for appstudio dev/e2e

test/metrics/metrics_test.go, testsupport/metrics.go, testsupport/wait/awaitility.go
this should avoid assertion failures in subsequent tests, when the baseline is off by 1 or more if the metrics were not reset totally when the next test started
=> test: ensure metrics are back to baseline after test

testsupport/tiers/checks.go
Updates test for readonly access for appstudio users to gitopsdeploymentmanagedenvironments, gitopsdeploymentrepositorycredentials, gitopsdeploymentsyncrun APIs.
Corresponding host-operator PR: https://github.com/codeready-toolchain/host-operator/pull/781
Corresponding book PR: https://github.com/redhat-appstudio/book/pull/90
=> Add test for read access to additional Core GitOps APIs

testsupport/tiers/checks.go
For security purposes, only the GitOps Service controllers should be able to create/modify/delete the `GitOpsDeployment*` resources, at this time.
* Note this does not effect the Environment API (Snapshots, Environments, SnapshotEnvironmentBindings, etc).
- *Book*: https://github.com/redhat-appstudio/book/pull/97
- *Host-operator*: https://github.com/codeready-toolchain/host-operator/pull/793
=> Remove write access to all GitOpsDeployment* resources, from all roles

test/e2e/parallel/space_cleanup_test.go, testsupport/wait/host.go
There are two reasons:
1. the `Wait*` functions don't return "NotFound" error if the poll times out, which results in a failed test if the Space/SpaceBinding wasn't found
2.  we don't have to wait the whole period - it's just there or not, so getting it directly is more suitable in this case
an example of the failed test: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/codeready-toolchain_toolchain-e2e/704/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1646501903141441536
```
Error Trace:	/go/src/github.com/codeready-toolchain/toolchain-e2e/test/e2e/parallel/space.go:97
/go/src/github.com/codeready-toolchain/toolchain-e2e/test/e2e/parallel/space_cleanup_test.go:138
/go/src/github.com/codeready-toolchain/toolchain-e2e/test/e2e/parallel/space_cleanup_test.go:30 …
```
=> fix: get Space & SpaceBinding directly in a loop

setup/operators/installtemplates/devspaces.yaml, setup/operators/installtemplates/devworkspace-operator.yaml, setup/operators/installtemplates/gitops-primer-template.yaml, setup/operators/installtemplates/kiali.yaml, setup/operators/installtemplates/openvino.yaml, setup/operators/installtemplates/rhoas.yaml, setup/operators/installtemplates/sbo.yaml, setup/operators/installtemplates/serverless-operator.yaml, setup/operators/installtemplates/web-terminal-operator.yaml
We don't really care about startingCSV for perf testing, so we can remove them to speed up the initial setup and reduce the maintenance work of updating startingCSV fields in subscriptions.
I verified the setup completes fine with these changes.
=> Remove starting CSVs to improve perf tooling setup

test/migration/setup_runner.go, test/migration/verify/verify_migration_test.go, testsupport/space.go
This change is needed because now usernames length is <= 20 chars, causing some of the migration test checks to fail.
=> make migration test usernames shorter

testsupport/space.go
- drop redundant check on the namespace since `VerifyNSTemplateSet` already executes `memberAwait.WaitForNamespace` , plus this check was assuming only 1 namespace (while the `VerifyNSTemplateSet` loops over the expected namespaces )
- remove workspace label check since the label will be dropped 
This is part of Jira: https://issues.redhat.com/browse/CRT-1776
=> fix: drop workspace label check from space testsupport

testsupport/space.go, testsupport/tiers/checks.go
This PR is for checking `appstudio.redhat.com/workspace_name ` label in the namespace
Paired with https://github.com/codeready-toolchain/host-operator/pull/798
=> Added Workspace Name Label check

testsupport/tiers/nstemplateset.go, testsupport/wait/member.go
Fix for https://issues.redhat.com/browse/CRT-1797
I was not able to reproduce the failure locally yet, but I've noticed that when `VerifyNSTemplateSet` is called here https://github.com/codeready-toolchain/toolchain-e2e/blob/cd125effc00c1f1235ad4383f778b81ecfb7e951/testsupport/space.go#L208-L215 there is not wait check for the `SpaceRoles` to be populated in the `NSTemplateSet`, while there is when invoked here https://github.com/codeready-toolchain/toolchain-e2e/blob/cd125effc00c1f1235ad4383f778b81ecfb7e951/testsupport/user_assertions.go#L190-L197
So my guess is that space roles are not  populated yet when `VerifyNSTemplateSet` is invoked by space.go:215 , causing less expected spaceroles then the actual ones:
```
member.go:2130: expected number of resources of kind 'RoleBindings' in …
```
=> fix: add wait for NSTemplateSet to have space roles populated

test/e2e/parallel/spacerequest_test.go, testsupport/wait/host.go
Since subSpaces now are recreated with same name, the space controller was very quick at provisioning a new subSpace and the test was failing while trying to wait for it to be deleted.
This PR checks that a new subSpace was recreated by comparing the creationTimestamp fields.
Jira bug: https://issues.redhat.com/browse/SANDBOX-52
Paired with: https://github.com/codeready-toolchain/host-operator/pull/809
=> fix: invalid number of subSpaces issue

test/metrics/metrics_test.go, testsupport/wait/member.go
e2e tests for https://github.com/codeready-toolchain/member-operator/pull/445
=> test(metrics): member-operator version metric

test/e2e/proxy_test.go
Related Issue: https://issues.redhat.com/browse/SANDBOX-226
This should hopefully address the flakiness.
The failure for reference:
```
=== RUN   TestSpaceLister/car_lists_workspaces
host.go:1718: waiting for Space 'car' with matching criteria
=== RUN   TestSpaceLister/car_gets_workspaces
=== RUN   TestSpaceLister/car_gets_workspaces/can_get_car_workspace
host.go:1718: waiting for Space 'car' with matching criteria
=== RUN   TestSpaceLister/car_gets_workspaces/cannot_get_bus_workspace
=== RUN   TestSpaceLister/bus_lists_workspaces
host.go:1718: waiting for Space 'bus' with matching criteria
host.go:1718: waiting for Space 'car' with matching criteria
=== RUN   TestSpaceLister/bus_gets_workspaces
=== RUN   TestSpaceLister/bus_gets_workspaces/can_get_bus_workspace
proxy_test.go:640: 
Error …
```
=> Add retries when getting workspace

setup/README.adoc
https://github.com/codeready-toolchain/toolchain-e2e/pull/756 introduced a bunch of changes which included removal of the -b flag but looks like I missed removing it in the README in a couple of places.
=> Remove batch flag from instructions

test/e2e/proxy_test.go, testsupport/tiers/checks.go
paired with https://github.com/codeready-toolchain/host-operator/pull/842
* it drops the obsolete proxy Role & RoleBinding (we didn't have the SA checks in place)
it also fixes a linter issue in proxy_test.go
=> drop obsolete proxy Role&RoleBinding

test/e2e/parallel/space_test.go
Extend `TestSubSpaces` to cover 3 level sub space hierarchy test scenario: `parentSpace` --> `subSpace` --> `subSubSpace`
Jira: https://issues.redhat.com/browse/ASC-398
Paired with: https://github.com/codeready-toolchain/host-operator/pull/843
=> feat: add support for SpaceBinding inheritance when there are multiple subspace levels

deploy/host-operator/appstudio-dev/toolchainconfig.yaml, deploy/host-operator/appstudio-e2e/toolchainconfig.yaml, deploy/host-operator/e2e-tests/toolchainconfig.yaml
Enable new SpaceBindingRequest controller in e2e test and dev environments.
The controller is not performing any action on SBR resources, it just reacts when one is created and triggers a reconcile loop. The logic of the controller among with e2e tests will be implemented next.
Jira: https://issues.redhat.com/browse/ASC-395
Paired with: https://github.com/codeready-toolchain/host-operator/pull/846
=> feat: create SpaceBindingRequest controller skeleton

testsupport/tiers/checks.go
See discussion in slack thread: https://redhat-internal.slack.com/archives/C02FANRBZQD/p1692011366722619
For issue https://issues.redhat.com/browse/RHTAPBUGS-595
ADR change: https://github.com/redhat-appstudio/book/pull/129
host-operator change: https://github.com/codeready-toolchain/host-operator/pull/849
=> adds deletecollection verb to components and applications

deploy/host-operator/appstudio-dev/toolchainconfig.yaml, deploy/host-operator/appstudio-e2e/toolchainconfig.yaml, deploy/host-operator/dev/toolchainconfig.yaml
based on latest discussions:
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1693460828997409
https://redhat-internal.slack.com/archives/CHK0J6HT6/p1693337601323839?thread_ts=1693316915.769479&cid=CHK0J6HT6
let's disable the phone verification step in dev environment - you know, to simplify it for other developers.
While doing so, I also noticed that the phone verification was enabled also in appstudio-e2e environment, which doesn't make any sense at all. So I disabled it there as well cc @jkopriva @sawood14012
=> disable phone verification in dev & appstudio environments

testsupport/tiers/checks.go
During efforts to onboard product components to RHTAP, the PVC resource utilization limit has resulted in regular `PipelineRun` failures.
See: https://github.com/codeready-toolchain/host-operator/pull/862
=> resources: increase the PVC claim limit to 30

setup/README.adoc
Hi, as new users the idler feature baffled us for a while. We were trying to deploy workloads for the first time and saw the pods our operator was trying to start get deleted and recreated in a loop and took a while to track down where the delete came from. Maybe having some note about the idler here would help other users who want to onboard operators?
Alternatively, maybe the CLI tool (`go run setup/main.go --help`) could mention what it does. Like:
```
-i, --idler-timeout string     overrides the default idler timeout, pods in the user's namespace are deleted after this duration (default "15s")
```
Thanks :bow:
=> Add note about idler configuration

test/e2e/parallel/registration_service_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go
paired with https://github.com/codeready-toolchain/host-operator/pull/867
=> verify that conflicts with Space names are being checked for compliantUsername

test/e2e/parallel/registration_service_test.go
the crc console URL is:
https://console-openshift-console.apps-crc.testing/
paired PR https://github.com/codeready-toolchain/registration-service/pull/349
=> CRC console doesn't contain .apps. substring

go.mod, go.sum, test/e2e/proxy_test.go
Update proxy (spacelister) e2e tests to check for the newly added `workspace.Status.AvailableRoles` field. The field should contain the Space roles for the NSTemplateTier. 
For example in the case of `appstudio` tier the list should be: `admin, maintainer, contributor`
Jira story: https://issues.redhat.com/browse/ASC-410
Related PRs:
- https://github.com/codeready-toolchain/toolchain-common/pull/327
Paired with: 
- https://github.com/codeready-toolchain/registration-service/pull/348
=> feat: Implement public API that will open SpaceBindings to end users through proxy part 1

quay.adoc
If a user intends to run end-to-end tests using quay as a repository, then the image `quay.io/<quay-username>/member-operator-console-plugin` needs to be publicly available.  Update the documentation for quay to reflect this.
=> Update documentation for usage with quay.io

.github/workflows/ci-build.yml, .github/workflows/ci-check-gomod.yml, .github/workflows/publish-operators-for-e2e-tests.yml
As of [June 2023][1], GitHub no longer uses node v12 within its actions runner by default.  They have been encouraging action authors to switch to node v16 and [encouraging users][2] to use the new versions of the actions when they become available, with the intent on removing node v12 sometime in the near future.
Bump the versions of the affected actions to bring this in line.
[1]: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
[2]: https://github.com/codeready-toolchain/host-operator/actions/runs/6421632076
=> ci: bump actions to silence node12 warnings

testsupport/wait/host.go
drop printing all resources in host namespace and print only the relevant ones to make reading of the build logs easier
=> drop printing all resources in host namespace

test/e2e/parallel/registration_service_test.go, test/metrics/metrics_test.go, testsupport/regsvc.go
Add e2e tests for the new registration service endpoint `GET /usernames/:username`.
Paired with: https://github.com/codeready-toolchain/registration-service/pull/361
Jira: https://issues.redhat.com/browse/ASC-413
=> feat: add usernames endpoint in reg-service

test/migration/setup_runner.go, test/migration/verify/verify_migration_test.go, testsupport/space/spacerequest.go
Make sure that existing spaces don't fall over during migrations.
See also: https://github.com/codeready-toolchain/host-operator/pull/891
=> add migration assertions for space requests

make/test.mk
Should fix the appstudio e2e issues:
```
Installing the Toolchain (Sandbox) operators in dev environment:
Cloning into '/tmp/toolchain-e2e'...
make[1]: Entering directory '/tmp/toolchain-e2e'
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin:/cli:/tmp/bin)
make deploy-e2e MEMBER_NS=toolchain-member-operator SECOND_MEMBER_MODE=false HOST_NS=toolchain-host-operator REGISTRATION_SERVICE_NS=toolchain-host-operator ENVIRONMENT=appstudio-dev E2E_TEST_EXECUTION=false IS_OSD= DEPLOY_LATEST=true
make[2]: Entering directory '/tmp/toolchain-e2e'
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin:/cli:/tmp/bin)
Preparing namespace for host operator toolchain-host-operator...
make create-project …
```
=> Fix issue for appstudio environment

testsupport/wait/member.go
E2e tests for https://github.com/codeready-toolchain/member-operator/pull/493
~~I've added a commit to temporarily disable validating webhook tests (just like in https://github.com/codeready-toolchain/toolchain-e2e/pull/809).~~
~~I plan to make a PR to enable the validating webhook tests after https://github.com/codeready-toolchain/member-operator/pull/493 is merged~~
=> E2e tests for K8sImagePuller validating webhook

test/e2e/default_tier_test.go, test/e2e/parallel/nstemplatetier_test.go
* extract one test that requires changes of the global config
* move the rest of the nstemplatetier_test.go into parallel test suite and add `t.Parallel()` to the tests it in
=> parallelize nstemplatetier test

test/e2e/e2e_test.go, test/e2e/toolchainstatus_test.go, test/metrics/metrics_test.go
extracts two sections that cannot be parallelized from the e2e test
1. verification of the TollchainStatus counters
2. the case when ToolchainConfig is modified to put ToolchainStatus in unready state
=> extract non-parallelizable parts from e2e test

test/e2e/no_user_identity_test.go, test/e2e/proxy_test.go
prepare proxy_test for moving to the parallel test suite by:
* extracting the logic that verifies skipped creation of user and identity
* removing changes of the ToolchainConfig
* moving the Space CR into the appstudio tier in the proxy test
=> extract test verifying skipped creation of user and identity

testsupport/user_setup.go
an attempt to fix:
```
=== NAME  TestE2EFlow
signup_request.go:334: 
Error Trace:	/tmp/toolchain-e2e/testsupport/signup_request.go:334
/tmp/toolchain-e2e/testsupport/signup_request.go:237
/tmp/toolchain-e2e/testsupport/user_setup.go:39
/tmp/toolchain-e2e/test/e2e/parallel/e2e_test.go:67
Post "https://registration-service-toolchain-host-20211636.apps.ci-op-sktqz02p-93ede.origin-ci-int-aws.dev.rhcloud.com/api/v1/signup": EOF
Test:       	TestE2EFlow
```
it's also closer to what we would see in production - each user would use different connection
=> Stop reusing connections

setup/users/create_users.go
UserSignups created by the setup tool were stuck with error:
```
spec:
identityClaims:
email: ''
preferredUsername: setup-0001
sub: setup-0001
states:
- approved
targetCluster: [redacted])
userid: ''
username: ''
status:
conditions:
- lastTransitionTime: '2023-12-20T14:46:24Z'
message: missing email at usersignup
reason: MissingUserEmail
status: 'False'
type: Complete
```
=> Fix setup create user missing email

test/e2e/parallel/user_workloads_test.go, testsupport/wait/host.go
Updating the test "TestIdlerAndPriorityClass" to fix some edge case failures.
- To fix limit error for docker "busybox" image pull 
- Make logger a less confusing
- Update the 'notification' variable to not use previous values while testing.
=> Updating the E2e Test "TestIdlerAndPriorityClass"

testsupport/wait/member.go
Removes the kubernetesimagepuller webhook tests in https://github.com/codeready-toolchain/toolchain-e2e/pull/840
Since the Kubernetes Image Puller Operator v1.1.0 provides its own webhook to limit image puller resources, this webhook on the member-operator side is not needed anymore: https://github.com/codeready-toolchain/member-operator/pull/526.
=> Remove kubernetesimagepuller webhook test

make/test.mk
remove zombie label selector `-l` and rename the var `member_name` to capitalized `MEMBER_NAME` to be consistent
=> fix: remove zombie label selector

setup/operators/operators.go, test/e2e/parallel/nstemplatetier_test.go, test/migration/setup_runner.go
While taking a look at `nstemplatetier_test.go`, I noticed that the wait package was being imported more than once. So, I ran `staticcheck ./...` locally to check if it occurs in other files. This PR cleans up the packages being imported more than once. In the future, maybe we can wonder if it makes sense to add this check to golangci lint config.
[SANDBOX-555](https://issues.redhat.com/browse/SANDBOX-555)
=> SANDBOX-555: clean up packages being imported more than once

testsupport/tiers/checks.go
Paired with: https://github.com/codeready-toolchain/host-operator/pull/993
[KONFLUX-2454](https://issues.redhat.com//browse/KONFLUX-2454)
=> Increase appstudio pods quota

make/test.mk
it causes failures in e2e tests https://storage.googleapis.com/test-platform-results/pr-logs/pull/codeready-toolchain_registration-service/416/pull-ci-codeready-toolchain-registration-service-master-e2e/1770125318879711232/build-log.txt
=> fix: drop type label selector from ToolchainCluster list

testsupport/util/log_timestamp.go, testsupport/wait/awaitility.go, testsupport/wait/host.go
Some jobs are failing with timeout when trying to get a space right after its creation.
- I have a theory. The `CreateWithCleanup` function used in `CreateSpaceAndSpaceBinding` is “delaying” the time between creating a Space and the SpaceBinding because it schedules the cleanup every time a resource is created. This "little" time window leads to the space being deleted after the get, because it does not "find" any SpaceBinding.
- In order to improve the logs, when the space is not found, we should get the name from `spaceToCreate` instead of `spaceCreated` (since space was not found, spaceCreated will be empty).
[SANDBOX-593](https://issues.redhat.com/browse/SANDBOX-593)
=> test: SANDBOX-593 create first Space and SpaceBinding and just after add them to the clean up task in CreateSpaceAndSpaceBinding

testsupport/tiers/checks.go
Change the default appstudio tier to parametrize all the compute-build values(cpu request/limit) and increase the large tier compute-build quotas. The numbers are quite high but one typical build-container task/pod have a limits of 20GiB and 18 cpus.
Also increase the secret quota for both tiers
Paired with https://github.com/codeready-toolchain/host-operator/pull/1014
[KFLUXINFRA-508](https://issues.redhat.com//browse/KFLUXINFRA-508)
=> Increase appstudiolarge tier quotas

test/e2e/parallel/spacerequest_test.go, testsupport/wait/host.go
Sometimes, in test `TestUpdateSpaceRequest`, after updating the space request tierName, the number of namespaces on the Space Request does not equal the number of namespaces of the Space. When we get the space, we need to ensure that we wait until the space has 2 namespaces (dev and stage, in this case).
[Job example](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_member-operator/562/pull-ci-codeready-toolchain-member-operator-master-e2e/1787595431182602240#1:build-log.txt%3A11488):
```
diffs:
invalid number of namespaces found in namespaceAccess. expected 1 but got 2
spacerequest_test.go:339:
Error Trace:	/tmp/toolchain-e2e/test/e2e/parallel/spacerequest_test.go:33911492
Error:      	Received unexpected error:timed out waiting for the …
```
=> test: SANDBOX-618 TestUpdateSpaceRequest - wait until the space has the desired number of namespaces

test/metrics/metrics_test.go, testsupport/user_setup.go
[Sporadically](https://search.dptools.openshift.org/?search=waited+for+metric+%27sandbox_master_user_records%5C%7B%5C%5Bdomain+external%5C%5D%5C%7D%27+to+reach+%272%27.&maxAge=336h&context=1&type=build-log&name=.*codeready-toolchain.*&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job), we are hitting this flaky test:
```
=== RUN   TestForceMetricsSynchronization/tampering_activation-counter_annotations/verify_metrics_did_not_change_after_restarting_pod_without_forcing_recount
awaitility.go:374: waiting for metric 'sandbox_master_user_records{[domain external]}' to reach '2'
awaitility.go:382: 
Error Trace:	/tmp/toolchain-e2e/testsupport/wait/awaitility.go:382
/tmp/toolchain-e2e/testsupport/wait/awaitility.go:117
/tmp/toolchain-e2e/test/metrics/metrics_test.go:702
Error: …
```
=> test: SANDBOX-624: TestForceMetricsSynchronization: EnsureMUR

make/test.mk
for some reason, when the first set of tests `./test/e2e` fails, then the metrics one are executed as well, apparently the `-failfast` flag doesn't apply to this. 
so let's run the metrics tests as part of separate execution to have it isolated, it could help with investigating this weird issue: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_member-operator/562/pull-ci-codeready-toolchain-member-operator-master-e2e/1790274999433564160
=> run metrics tests separate

test/e2e/toolchaincluster_test.go
We need to copy the secret that is referenced by the ToolchainCluster CR. 
What happens now is that the migration code in ToolchainCluster controller updates the secret with the expected label `toolchain.dev.openshift.com/toolchain-cluster` set to the name of the ToolchainCluster CR, but since the same secret is used by two ToolchainClusters then there is a huge number of immediate updates of the same secret in a row when the controller is changing the label from one value to another. This increase of updates can cause instability of the controller/operator that we can see in openshift-ci around the time when this particular test is running.
**EDIT**: Taking a second look at the ToolchainCluster controller, the flow described above is probably not valid. The ToolchainCluster controller …
=> fix flaky: copy ToolchainCluster secret

testsupport/tiers/checks.go
This change adds a Role and RoleBinding to the tenant use to CRUD on SecretStore and ExternalSecret CRs provided by external-secrets.io
This is meant for testing if this can enable tenants to create SecretStore and ExternalSecret from their own self-hosted or managed secrets backend
Paired PR in `codeready-toolchain/host-operator` - https://github.com/codeready-toolchain/host-operator/pull/1034
=> Add rules for SecretStore and ExternalSecret CRs 

test/e2e/toolchaincluster_test.go
Related PRs:
- member operator: https://github.com/codeready-toolchain/member-operator/pull/571
=> KUBESAW-16: Make sure the toolchain cluster token secrets are labeled also in the member operator

testsupport/tiers/checks.go
Intended role was not applied properly due to including version in apiGroups.
Removing the same as part of this PR
https://github.com/codeready-toolchain/host-operator/pull/1038
=> Remove version from apiGroups

test/e2e/user_management_test.go
Add a wait condition to ensure that the scheduled deactivation time is set before continuing.
=> Fix flaky e2e test

test/e2e/default_tier_test.go, test/e2e/no_user_identity_test.go, test/e2e/parallel/e2e_test.go, test/e2e/parallel/nstemplatetier_test.go, test/e2e/parallel/proxy_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/retarget_test.go, test/e2e/parallel/serviceaccount_test.go, test/e2e/parallel/space_cleanup_test.go, test/e2e/parallel/space_test.go, test/e2e/parallel/spacebindingrequest_test.go, test/e2e/parallel/usersignup_test.go, test/e2e/parallel/web_console_plugin_test.go, test/e2e/space_autocompletion_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/metrics/metrics_test.go, test/migration/setup_runner.go, testsupport/signup_request.go, testsupport/space/space.go, testsupport/user_setup.go
As discussed [here](https://github.com/codeready-toolchain/toolchain-e2e/pull/986#discussion_r1622348683), we can benefit from also returning space in `Resources`.
However, after discussing in this [PR's conversation](https://github.com/codeready-toolchain/toolchain-e2e/pull/991#discussion_r1625880758), we can move forward to drop Resources and return space and token in `Execute`.
[SANDBOX-629](https://issues.redhat.com/browse/SANDBOX-629)
=> test: SANDBOX-629: drop Resources and also return space and token in Execute

testsupport/tiers/checks.go
appstudio:
* Parametrize request storage, keep same value of 200Gi
* Set build CPU request to half of limit, i.e. 60.
appstudiolarge:
* Set request storage to double of appstudio tier, i.e. 400Gi.
* Set build CPU request to half of limit, i.e. 240.
* Set build memory request to half of limit, i.e. 256Gi.
Paired with https://github.com/codeready-toolchain/host-operator/pull/1045
[KFLUXINFRA-632](https://issues.redhat.com//browse/KFLUXINFRA-632)
=> Increase quotas in appstudio and appstudiolarge

test/e2e/parallel/space_test.go, test/e2e/space_autocompletion_test.go, testsupport/space/space.go
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/codeready-toolchain_member-operator/562/pull-ci-codeready-toolchain-member-operator-master-e2e/1790274999433564160
Space auto-completion test was creating Space & SpaceBinding CRs using a function that wasn't executed in a loop. The test is not running in a parallel test suite (so it shouldn't be theoretically a big deal), but there was apparently some reason for not having the SpaceBinding present and thus the NSTemplateSet didn't have the SpaceRoles set and was being terminated.
So, to avoid any unexpected scenarios, I'm changing it so it uses the loop that ensures that Space & SpaceBinding is always created together.
As part of this investigation I noticed that one parallel test case was using the same function - …
=> fix flaky: create Space & SpaceBinding always in a loop

setup/operators/operators_test.go, test/e2e/parallel/registration_service_test.go
Related to https://github.com/codeready-toolchain/registration-service/pull/436
New tests to verify that:
1. the metrics are _not_ exposed on the public Route
2. the expected metrics are available from the new Service[1] - tested
from the outside of the cluster by creating a temporary Route
[1]: see https://github.com/codeready-toolchain/host-operator/pull/1050 (required to run the e2e tests)
=> test: registration service metrics

make/test.mk, test/e2e/parallel/nstemplatetier_test.go, testsupport/tiers/templaterefs.go
1. clone latest version of ksctl
2. install it locally
3. copy appstudio tiers (from host-operator) into /tmp folder
4. run `ksctl generate nstemplatetiers` for the appstudio tiers
5. apply the generated TierTemplates (and add an annotation to all resources)
6. verify in the tests that the NSTemplateTier doesn't get overridden and keeps the generated TierTemplates
you know, just to make sure that this will work as soon as Konflux team moves it to a infra-deployments
[KUBESAW-62](https://issues.redhat.com/browse/KUBESAW-62)
=> add verification of (re)generating appstudio tiers via ksctl

make/ksctl.mk, make/test.mk
simplified the installation of the ksctl binary and moved it to a separate makefile to not mix the things in the huge test file.
Later, we can think about:
1. either incorporating ksctl into the pairing mechanism
2. or specify the ksctl dependency in the go.mod file
But for now, let's do this simple install process and use always the master branch. In this way, we can also easily point any PR to a specific fork/branch if needed (to test any fixes of bugs).
The new `ksctl` makefile target can be also used later for making sure that the binary is present for example before calling `ksctl adm register-member` command.
=> install ksctl via go install in a separate file

.github/workflows/ci-build.yml, .github/workflows/publish-operators-for-e2e-tests.yml
uses go-version-file instead of go-version. One less place to change when making updates.
Changes order in github action to first checkout code and then install go.
related PRs:
https://github.com/codeready-toolchain/api/pull/434
https://github.com/codeready-toolchain/toolchain-common/pull/415
https://github.com/codeready-toolchain/member-operator/pull/584
https://github.com/codeready-toolchain/registration-service/pull/445
https://github.com/codeready-toolchain/host-operator/pull/1060
=> SANDBOX-677 use go-version-file

go.mod, go.sum, quay.adoc, test/e2e/parallel/space_test.go
Pendo has been decommisioned, we don't need this plugin anymore
=> remove webConsolePlugin from ToolchainClusterConfig (go mod)

make/test.mk, test/e2e/parallel/e2e_test.go, testsupport/wait/member.go
fix for https://github.com/codeready-toolchain/toolchain-e2e/pull/1027#issuecomment-2273284916
We need to replicate the whole member config from the default one and set only `.webhook.deploy: false` for it
=> fix: replicate member-config for the second member operator

make/ksctl.mk, make/test.mk
Since the e2e test setup is increasingly dependent on ksctl commands, I introduced a possibility of pairing between toolchain-e2e and ksctl.
* It's only one-directional  - the e2e tests are not executed in ksctl repo for now. It can be changed later.
* It's not included into the limit that we can pair only one PR (host/member/reg-service) with only one PR from toolchain-e2e repo. In other words, it can be combined with it.
* it's not included in the migration test suite for now
* local execution uses ksctl version from master if not specified otherwise via env variables `USE_INSTALLED_KSCTL` or `KSCTL_REPO_PATH`. The UX can be changed later.
paired PR https://github.com/kubesaw/ksctl/pull/58 (expecting to fail when generating tier manifests)
=> enable pairing with branches from ksctl repository

go.mod, go.sum, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/socialevent_test.go, testsupport/wait/host.go
Paired with https://github.com/codeready-toolchain/registration-service/pull/454
=> Set target cluster for social events

make/ksctl.mk
* pairing is not executed if `DEPLOY_LATEST` is set to `true` - this means, in appstudio makefile targets
* added more logs so it's clear what version is gonna be used
* extracted git cloning and merging to a separate target - the reason is that the if statements are evaluated at the beginning of the target, so setting it in the middle of it doesn't have any effect on the result of the if statement. Thus, there were problems with the `ifneq ($(strip $(REMOTE_KSCTL_BRANCH)),)`
TBH, the special behavior of makefile targets drives me crazy and I'm thinking about moving it to a bash script.
I'll take a look at the options and think about the best approach.
=> fix ksctl pairing

test/e2e/parallel/proxy_test.go
This PR add test scenarios in which a banned user cannot get and list workspaces.
It is related to this PR: https://github.com/codeready-toolchain/toolchain-e2e/pull/1036 which adds tests for banned users in proxy.
=> add banned user scenario to get and list workspaces tests

make/ksctl.mk
enabled ksctl pairing only in openshift-ci and in codeready-toolchain org only, and unless CI_DISABLE_PAIRING is not set to true
https://github.com/codeready-toolchain/toolchain-e2e/pull/1032#issuecomment-2303918844
https://github.com/codeready-toolchain/toolchain-e2e/pull/1034#issuecomment-2297326327
=> pair only in codeready-toolchain org & introduce CI_DISABLE_PAIRING var

go.mod, go.sum
This updates to the latest toolchain-common version. It should have been part of https://github.com/codeready-toolchain/toolchain-e2e/pull/1012 that I mistakenly merged with toolchain-common reference that is a commit behind.
=> Upgrade to the latest toolchain-common version

test/e2e/toolchaincluster_test.go
Update the tests to not distinguish between member and host because both should now read the connection details from the kubeconfig in TC secret.
Related PRs:
* member-operator: https://github.com/codeready-toolchain/member-operator/pull/595
=> Update the tests to not distinguish between member and host

test/e2e/parallel/proxy_test.go
Linked to https://github.com/codeready-toolchain/registration-service/pull/455 and https://github.com/codeready-toolchain/host-operator/pull/1079
Signed-off-by: Francesco Ilario <filario@redhat.com>
=> add e2e tests for banneduser

make/test.mk
from the docs https://pkg.go.dev/cmd/go#hdr-Testing_flags
```
...
By default, -parallel is set to the value of GOMAXPROCS.
Setting -parallel to values higher than GOMAXPROCS may cause degraded
performance due to CPU contention, especially when fuzzing.
...
```
=> remove -parallel flag

setup/users/create_users.go, setup/users/create_users_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/spacerequest_test.go, test/e2e/toolchaincluster_test.go, test/migration/verify/verify_migration_test.go, testsupport/toolchain_status_assertions.go, testsupport/wait/awaitility.go, testsupport/wait/host.go
Instead, use their replacements in the ToolchainCluster status. This will enable us to remove the fields from the spec and only rely on the kubeconfig (and the status fields that project the values out of the kubeconfig).
=> Don't use the ToolchainCluster.Spec fields

testsupport/wait/awaitility.go
A trivial fix to the log message so that it reflects what the code actually checks for.
=> Fix the outdated message talking about the namespace label.

README.adoc, make/test.mk, test/migration/setup/setup_migration_test.go, testsupport/init.go, testsupport/wait/awaitility.go
To reuse the function `WaitForDeployments` in WA E2E tests, we need to refactor `WaitForDeployments` to take into consideration when SECOND_MEMBER_MODE is set to false.
[SANDBOX-816](https://issues.redhat.com/browse/SANDBOX-816)
=> test: SANDBOX-816 refactor WaitForDeployments

README.adoc, make/dev.mk, make/test.mk
- add `deploy-toolchain-resources-e2e` to deploy the same resources as `make test-e2e` but doesn't run tests. It will be useful for wa
[SANDBOX-811](https://issues.redhat.com/browse/SANDBOX-811)
=> add deploy-toolchain-resources-e2e

test/e2e/parallel/registration_service_test.go
"TestActivationCodeVerification" failed twice, for now, with `Operation cannot be fulfilled on socialevents.toolchain.dev.openshift.com`. I guess this is happening because when we call`WaitForSocialEvent`, we are not checking that the resource was in a ready state. So, when we update the resource right after, the resource is not ready in some edge cases and we do not have the latest version of the resource, causing the `Operation cannot be fulfilled on socialevents.toolchain.dev.openshift.com`.
[SANDBOX-838](https://issues.redhat.com/browse/SANDBOX-838)
=> fix: SANDBOX-838 check that SocialEvent is in a ready state when WaitForSocialEvent after creation

test/migration/setup/setup_migration_test.go, testsupport/wait/member.go
It's the follow up to https://github.com/codeready-toolchain/toolchain-e2e/pull/1070 to re-enable the webhook tests
=> Reinstate webhook tests

testsupport/wait/awaitility.go
This PR makes `getAndPrint` exportable. It will be useful for wa
[SANDBOX-858](https://issues.redhat.com/browse/SANDBOX-858)
=> SANDBOX-858: make getAndPrint exportable

test/e2e/no_user_identity_test.go, test/e2e/parallel/e2e_test.go, test/e2e/parallel/nstemplatetier_test.go, test/e2e/parallel/proxy_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/socialevent_test.go, test/e2e/parallel/space_cleanup_test.go, test/e2e/parallel/space_test.go, test/e2e/parallel/usersignup_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/metrics/metrics_test.go, test/migration/setup_runner.go, testsupport/deactivation.go, testsupport/signup_request.go, testsupport/spaceprovisionerconfig/spaceprovisionerconfig.go, testsupport/tiers/tier_setup.go, testsupport/wait/awaitility.go, testsupport/wait/host.go
#1071 addressed a potential fix, but to ensure we do not face it in the future, we should do the update call in a loop. 
Since other update calls are not being done in a loop, this PR addressed it as well. 
[SANDBOX-838](https://issues.redhat.com/browse/SANDBOX-838)
=> SANDBOX-838: loop update calls

test/e2e/no_user_identity_test.go, test/e2e/parallel/e2e_test.go, test/e2e/parallel/nstemplatetier_test.go, test/e2e/parallel/proxy_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/parallel/retarget_test.go, test/e2e/parallel/serviceaccount_test.go, test/e2e/parallel/socialevent_test.go, test/e2e/parallel/space_cleanup_test.go, test/e2e/parallel/space_test.go, test/e2e/parallel/spacebindingrequest_test.go, test/e2e/parallel/spaceprovisionerconfig_test.go, test/e2e/parallel/spacerequest_test.go, test/e2e/parallel/user_workloads_test.go, test/e2e/parallel/usersignup_test.go, test/e2e/user_management_test.go, test/e2e/usersignup_test.go, test/metrics/metrics_test.go, test/migration/setup_runner.go, testsupport/deactivation.go, testsupport/signup_request.go, testsupport/spaceprovisionerconfig/spaceprovisionerconfig.go, testsupport/tiers/tier_setup.go, testsupport/wait/awaitility.go, testsupport/wait/host.go, testsupport/wait/member.go
This PR cleans up all the update functions that are very similar to the `Update` generic function, addressing the necessary changes.  
Please, note that I did not clean up `UpdateSpaceBindingRequest` because `UpdateTestUpdateSpaceBindingRequest` returns err when there is an error while updating, it is needed for this [assertion](https://github.com/codeready-toolchain/toolchain-e2e/blob/master/test/e2e/parallel/spacebindingrequest_test.go#L212)
[SANDBOX-838](https://issues.redhat.com/browse/SANDBOX-838)
=> apply generic update

test/e2e/parallel/nstemplatetier_test.go, testsupport/init.go, testsupport/wait/host.go
This PR is to remove the NSTemplateTier.Status.Updates field(already optional in API) and its related code since it's not used anywhere
Paired and Related PR
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1115
=> KUBESAW-248: Drop NSTemplateTier.Status.Updates field

test/e2e/parallel/space_test.go
make sure that the space is unblocked for the cleanup, even for the cases when the test execution is stopped in the middle and the sub-test (that is supposed to unblock the space) is not triggered: https://redhat-internal.slack.com/archives/C06MJ2DVBU4/p1736342796950679?thread_ts=1736333943.812749&cid=C06MJ2DVBU4
=> fix(flaky): ensure that the space is always unblocked for its deletion

test/e2e/parallel/e2e_test.go
the same idea as for https://github.com/codeready-toolchain/toolchain-e2e/pull/1090
=> fix(flaky): ensure that the CM finalizer is always removed

README.adoc
`deploy-toolchain-resources-e2e` is actually `deploy-single-member-e2e`
=> docs: correct README

README.adoc, make/test.mk
`deploy-single-member-e2e` was added to be used in wa. Since we do not need a pairing mechanism there, we can simply use the latest and greatest images of Toolchain operators
[SANDBOX-812](https://issues.redhat.com/browse/SANDBOX-812)
=> change deploy-single-member-e2e to deploy-single-member-e2e-latest

test/e2e/parallel/registration_service_test.go
paired with https://github.com/codeready-toolchain/registration-service/pull/501
[KUBESAW-254](https://issues.redhat.com/browse/KUBESAW-254)
=> reflect dropped userID support for UserSignup names

test/e2e/parallel/proxy_test.go, testsupport/wait/awaitility.go
create our own ConfigMap and check that it exists to avoid any flakiness that we faced in many e2e tests before
wrt - [SANDBOX-836](https://issues.redhat.com/browse/SANDBOX-836)
=> fix kube-root-ca.crt not found

testsupport/cleanup/clean.go, testsupport/metrics/metrics.go
no need for dozens of logs such as:
```
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
clean.go:205: the related MasterUserRecord: foo is deleted as well
...
```
=> reduce amount of logs during cleanup

testsupport/init.go, testsupport/wait/host.go
This PR is for the fix of e2e [Failures](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/codeready-toolchain_host-operator/1130/pull-ci-codeready-toolchain-host-operator-master-e2e/1887805053301952512/build-log.txt) .
The parallel e2e test are making concurrent writes to the global `Scheme` variable, used in the package `testsupport/wait` .
This PR ensures that a new Scheme is always used instead of the global one.
=> fix: panic for concurrent writing in parallel test (scheme)

test/e2e/parallel/nstemplatetier_test.go
to fix flakiness 
https://storage.googleapis.com/test-platform-results/pr-logs/pull/codeready-toolchain_registration-service/506/pull-ci-codeready-toolchain-registration-service-master-e2e/1889236061419212800/build-log.txt
```
nstemplatetier_test.go:570: 
Error Trace:	/tmp/toolchain-e2e/test/e2e/parallel/nstemplatetier_test.go:570
/tmp/toolchain-e2e/test/e2e/parallel/nstemplatetier_test.go:464
Error:      	[]v1alpha1.Parameter{v1alpha1.Parameter{Name:"DEPLOYMENT_QUOTA", Value:"60"}} does not contain v1alpha1.Parameter{Name:"DEPLOYMENT_QUOTA", Value:"100"}
Test:       	TestTierTemplateRevision/update_of_tiertemplate_should_trigger_creation_of_new_TTR/update_of_the_NSTemplateTier_parameters_should_trigger_creation_of_new_TTR
Messages:   	Unable to find required …
```
=> wait for updates of revisions in NSTemplateTier.Status

test/e2e/parallel/nstemplatetier_test.go, testsupport/tiers/templaterefs.go, testsupport/tiers/tier_setup.go, testsupport/wait/host.go
e2e tests for : https://github.com/codeready-toolchain/host-operator/pull/1136
Jira:  https://issues.redhat.com/browse/KUBESAW-259
=> feat: cleanup revision entries from nstemplatetier

.golangci.yml
The Golanci-lint action recently changed the `golangci-lint verify` command to by default be true. [Change](https://github.com/golangci/golangci-lint-action/releases/tag/v6.5.0)
This broke our Golanci-lint CI [errorrepo1](https://github.com/codeready-toolchain/toolchain-common/actions/runs/13364924316/job/37328247752?pr=454#step:4:37).
The fix is to remove the additional parameter which the verify doesn't allow
Similar Prs
- Member-operator - https://github.com/codeready-toolchain/member-operator/pull/626
- Host Operator - https://github.com/codeready-toolchain/host-operator/pull/1143
- Toolchain-e2e - https://github.com/codeready-toolchain/toolchain-e2e/pull/1120
- Toolchain - common - https://github.com/codeready-toolchain/toolchain-common/pull/458
- Api - …
=> update Golanci-lint config

test/migration/setup_runner.go, test/migration/verify/verify_migration_test.go, testsupport/init.go
This could minimize the test flakiness. It waits at the beginning of each test suite (and at the end of the migration test suites) until the ToolchainStatus is ready and updated, this means that the client-cache is initialized, the controller has started, and ToolchainStatus in sync with the counter.
=> wait until ToolchainStatus is updated and in sync with counter

test/e2e/parallel/proxy_test.go
When there is a failure in the parallel test suite, it may happen that the whole e2e test fails with timeout panic:
https://storage.googleapis.com/test-platform-results/pr-logs/pull/openshift_release/61582/rehearse-61582-pull-ci-codeready-toolchain-host-operator-master-e2e/1889811595995910144/build-log.txt
https://storage.googleapis.com/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/1111/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1889337786046091264/build-log.txt
The reason is that:
* the watcher logic is executed as a sub-test inside of the goroutine
* the WaitGroup is incremented in the parent test (outside of the go routine) 
When one parallel test fails, then the test executor won't start any new sub-test. This means that if the failure happens before …
=> avoid timeout panic when a parallel test fails

go.mod, go.sum, test/e2e/parallel/nstemplatetier_test.go, testsupport/space/space.go, testsupport/tiers/tier_setup.go, testsupport/user_assertions.go
This PR is to update the space controller to compute the tier-hash label value using the NSTemplateTier.Status.Revisions field so that it can match outdated spaces using the new revisions mechanism.
Jira-Link - [KUBESAW-147](https://issues.redhat.com/browse/KUBESAW-147)
Related PR
- Toolchain-commmon - https://github.com/codeready-toolchain/toolchain-common/pull/454
Paired with 
- Host-Operator - https://github.com/codeready-toolchain/host-operator/pull/1135
=> KUBESAW-147: Space controller updates tier-hash label based on the NSTemplateTier.Status.Revisions field

go.mod, go.sum, test/metrics/metrics_test.go, testsupport/metrics/metrics.go, testsupport/wait/awaitility.go, testsupport/wait/host.go
Gets the histogram `sandbox_user_signup_provision_time` and verifies that it is updated with the provisioned time of a user that was automatically approved
paired with https://github.com/codeready-toolchain/host-operator/pull/1148
depends on https://github.com/codeready-toolchain/registration-service/pull/515
[SANDBOX-957](https://issues.redhat.com/browse/SANDBOX-957)
=> verify histogram with measured provision time

test/metrics/metrics_test.go
paired with https://github.com/codeready-toolchain/host-operator/pull/1150
[SANDBOX-957](https://issues.redhat.com/browse/SANDBOX-957)
=> verify skipped phone-verified accounts in tracking provisioned time

test/e2e/user_management_test.go
paired PR https://github.com/codeready-toolchain/registration-service/pull/520
[KUBESAW-267](https://issues.redhat.com/browse/KUBESAW-267)
=> verify that reg-service returns 403 when user is banned

.github/workflows/ci-build.yml, .golangci.yml, setup/metrics/client.go, test/e2e/parallel/proxy_test.go, test/e2e/parallel/registration_service_test.go, test/e2e/user_management_test.go, testsupport/space/spacerequest.go, testsupport/spacebinding/spacebindingrequest.go, testsupport/tiers/checks.go, testsupport/tiers/tier_setup.go, testsupport/wait/diff.go, testsupport/wait/host.go, testsupport/wait/member.go
upgraded `.golangci.yml` with `golangci-lint migrate`
include fixes suggested by `golangci-lint run -c ./.golangci.yml`
=> chore(build): migrate to golangci-lint@v2 and golangci-lint-action@v7

deploy/crds/README.adoc, deploy/crds/aap.ansible.com_ansibleautomationplatforms.yaml, test/e2e/parallel/user_workloads_test.go, testsupport/wait/member.go
This is an attempt to create a simple test for the AAP idler.
- it creates an AAP instance (using a mock AAP CRD) with one Deployment owned by it
- Waits for the AAP.Spec.idler_aap to be set to "true" by the idler.
- The underlying pods are still running since there is no AAP controller to shut them down
=> Tests for AAP idler

testsupport/tiers/checks.go
follow-up of https://github.com/codeready-toolchain/member-operator/commit/e209d75d71828009f4da35d099fcb4d07900664a
https://storage.googleapis.com/test-platform-results/pr-logs/pull/codeready-toolchain_toolchain-e2e/1164/pull-ci-codeready-toolchain-toolchain-e2e-master-e2e/1938483163353321472/build-log.txt
```
checks.go:2147: 
Error Trace:	/go/src/github.com/codeready-toolchain/toolchain-e2e/testsupport/tiers/checks.go:2147
/go/src/github.com/codeready-toolchain/toolchain-e2e/testsupport/tiers/nstemplateset.go:74
/usr/local/go/src/runtime/asm_amd64.s:1695
clusterroles.rbac.authorization.k8s.io "appstudio-pipelines-runner" not found
Test:       	TestAfterMigration
```
=> drop appstudio-pipelines-runner ClusterRole from tests

test/e2e/parallel/proxy_test.go
We started to see flakiness in TestProxyFlow on the PR to [upgrade the cluster to version 4.19 on the release side](https://github.com/openshift/release/pull/66283). Openshift 4.19 uses Kubernetes 1.32, which has now ResilientWatchCacheInitialization feature enabled. For more info: https://redhat-internal.slack.com/archives/CHK0J6HT6/p1751015099622649
[SANDBOX-1239](https://issues.redhat.com/browse/SANDBOX-1239)
=> SANDBOX-1239: add retry when connecting to websocket

test/e2e/default_tier_test.go, test/e2e/parallel/nstemplatetier_test.go, test/e2e/parallel/space_test.go, testsupport/tiers/checks.go, testsupport/wait/host.go, testsupport/wait/stringify_test.go
This updates the e2e tests to not rely on the `advanced` tier to be present.
Related PRs:
* host-operator: https://github.com/codeready-toolchain/host-operator/pull/1177
* ksctl: https://github.com/kubesaw/ksctl/pull/120
=> The advanced ns template tier was removed
